### PR TITLE
Status: Add microshift as part of status

### LINKED ISSUE #3592: [BUG] Status reports podman preset while microshift is running
### General information

  * OS: macOS
  * Hypervisor: hyperkit 
  * Did you run `crc setup` before starting it: Yes
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.16.0+05b62a75
OpenShift version: 4.12.9
Podman version: 4.4.1
```
  
## CRC status
```bash
DEBU CRC version: 2.16.0+05b62a75
DEBU OpenShift version: 4.12.9
DEBU Podman version: 4.4.1
DEBU Running 'crc status'
CRC VM:          Running
RAM Usage:       1.196GB of 3.913GB
Disk Usage:      4.746GB of 16.1GB (Inside the CRC VM)
Cache Usage:     72.04GB
Cache Directory: /Users/yevhen/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
- preset                                : microshift
```

## Host Operating System
```bash
ProductName:		macOS
ProductVersion:		13.3
BuildVersion:		22E252
```

### Steps to reproduce

  1.  Configure crc to use `microshift` bundle
  2. Start crc with `microshift` bundle
  3. Call `curl -GET -i --unix-socket <home>/.crc/crc-http.sock http://localhost/api/status` to get status in json 

### Expected
```json
{"CrcStatus":"Running", "Preset":"microshift", ...}
```

### Actual
```json
{"CrcStatus":"Running", "Preset":"podman",  ...}
```

### PR DESCRIPTION
**Pull request by praveenkumar**
With this patch now for microshift preset user will get following
output.
```
$ ./crc status
CRC VM:          Running
MicroShift:      Running (v4.12.9)
RAM Usage:       1.144GB of 3.913GB
Disk Usage:      4.647GB of 16.1GB (Inside the CRC VM)
Cache Usage:     208.9GB
Cache Directory: /home/prkumar/.crc/cache

$ ./crc status -ojson
{
  "success": true,
  "crcStatus": "Running",
  "microshiftStatus": "Running",
  "microshiftVersion": "4.12.9",
  "diskUsage": 4646580224,
  "diskSize": 16095641600,
  "cacheUsage": 208867411129,
  "cacheDir": "/home/prkumar/.crc/cache",
  "ramSize": 3912945664,
  "ramUsage": 1144094720,
  "preset": "microshift"
}
```

Fixes: #3592

### CODE REVIEW

**Review by evidolob — APPROVED** [review]
This work as expected:

```json
{"CrcStatus":"Running",
"OpenshiftStatus":"",
"MicroShiftStatus":"Running",
"MicroShiftVersion":"4.12.9",
"DiskUse":4739710976,
"DiskSize":16095641600,
"RAMUse":979648512,
"RAMSize":3913109504,
"Preset":"microshift"
}
```

File: pkg/crc/machine/status.go [hunk 1]
```diff
@@ -57,13 +64,20 @@ func (client *client) Status() (*types.ClusterStatusResult, error) {
...
 		DiskSize:  diskSize,
 	}
-	if vm.bundle.IsOpenShift() {
+	switch {
+	case vm.bundle.IsPodman():
+		logging.Info("podman")
+		clusterStatusResult.PodmanVersion = vm.bundle.GetPodmanVersion()
+		clusterStatusResult.Preset = preset.Podman
+	case vm.bundle.IsMicroshift():
+		logging.Info("microshift")
```
Comment (anjannath) [inline pkg/crc/machine/status.go]: i think this `log.Info` is unintended and left over from debugging

Comment (praveenkumar) [reply pkg/crc/machine/status.go]: @anjannath ah yes, I will remove those.

Comment (praveenkumar) [reply pkg/crc/machine/status.go]: @anjannath Updated.

**Review by anjannath — APPROVED** [review]

File: pkg/crc/machine/start.go [hunk 2]
```diff
@@ -295,13 +295,13 @@ func (client *client) Start(ctx context.Context, startConfig types.StartConfig)
 		return nil, errors.Wrap(err, "Error getting the machine state")
 	}
 	if vmState == state.Running {
-		if !vm.bundle.IsOpenShift() {
-			logging.Infof("A CRC VM for Podman %s is already running", vm.bundle.GetPodmanVersion())
+		if vm.bundle.IsPodman() {
+			logging.Infof("A CRC VM for %s %s is already running", startConfig.Preset.ForDisplay(), vm.bundle.GetPodmanVersion())
```
Comment (cfergeau) [inline pkg/crc/machine/start.go]: This can be changed to `logging.Infof("A CRC VM for %s %s is already running", startConfig.Preset.ForDisplay(), vm.bundle.GetVersion())` and be moved out of the `if {}` block.

```
  logging.Infof("A CRC VM for %s %s is already running", startConfig.Preset.ForDisplay(), vm.bundle.GetVersion())
  if vm.bundle.IsPodman() {
    return &types.StartResult{
				Status: vmState,
			}, nil
  }
  clusterConfig, err := getClusterConfig(vm.bundle)
  if err != nil {
    return nil, errors.Wrap(err, "Cannot create cluster configuration")
```

File: pkg/crc/cluster/clusteroperator.go [hunk 3]
```diff
@@ -80,7 +80,7 @@ func (status *Status) IsReady() bool {
 }
 
 func GetClusterOperatorsStatus(ctx context.Context, ip string, kubeconfigFilePath string) (*Status, error) {
-	lister, err := kubernetesClient(ip, kubeconfigFilePath)
+	lister, err := openShiftClient(ip, kubeconfigFilePath)
```
Comment (cfergeau) [inline pkg/crc/cluster/clusteroperator.go]: fwiw, `openshiftClient` would be easier to read

File: cmd/crc/cmd/status.go [hunk 4]
```diff
@@ -132,6 +134,7 @@ func createBars(cpuUse []int64, writer io.Writer) (ramBar *pb.ProgressBar, cpuBa
 func getStatus(client *daemonclient.Client, cacheDir string) *status {
 
 	clusterStatus, err := client.APIClient.Status()
+
```
Comment (cfergeau) [inline cmd/crc/cmd/status.go]: unneeded change

File: cmd/crc/cmd/status.go [hunk 5]
```diff
@@ -217,6 +225,13 @@ func openshiftStatus(status *status) string {
 	return string(status.OpenShiftStatus)
 }
 
+func microShiftStatus(status *status) string {
+	if status.MicroShiftVersion != "" {
+		return fmt.Sprintf("%s (v%s)", status.MicroShiftStatus, status.MicroShiftVersion)
+	}
+	return string(status.OpenShiftStatus)
```
Comment (cfergeau) [inline cmd/crc/cmd/status.go]: MicroShiftStatus?

File: pkg/crc/machine/status.go [hunk 6]
```diff
@@ -146,6 +158,24 @@ func getOpenShiftStatus(ctx context.Context, ip string) types.OpenshiftStatus {
...
+	sd := systemd.NewInstanceSystemdCommander(sshRunner)
+	microShiftServiceState, err := sd.Status("microshift")
+	if err != nil {
+		logging.Debugf("failed to get microshift service status: %v", err)
+		return types.OpenshiftUnreachable
+	}
+	if microShiftServiceState == sdState.Running {
+		return types.OpenshiftRunning
+	}
+	return types.OpenshiftStopped
```
Comment (cfergeau) [inline pkg/crc/machine/status.go:172]: fwiw, `crc start` waits for `oc get nodes` to be successful before deciding the cluster was started successfully, maybe `status` should use the same criterion.

File: cmd/crc/cmd/status.go [hunk 7]
```diff
@@ -39,19 +39,21 @@ var statusCmd = &cobra.Command{
...
-	RAMUsage         int64                        `json:"ramUsage,omitempty"`
-	Preset           preset.Preset                `json:"preset"`
+	Success           bool                         `json:"success"`
+	Error             *crcErrors.SerializableError `json:"error,omitempty"`
+	CrcStatus         string                       `json:"crcStatus,omitempty"`
+	OpenShiftStatus   types.OpenshiftStatus        `json:"openshiftStatus,omitempty"`
+	OpenShiftVersion  string                       `json:"openshiftVersion,omitempty"`
+	MicroShiftStatus  types.OpenshiftStatus        `json:"microshiftStatus,omitempty"`
+	MicroShiftVersion string                       `json:"microshiftVersion,omitempty"`
+	PodmanVersion     string                       `json:"podmanVersion,omitempty"`
```
Comment (cfergeau) [inline cmd/crc/cmd/status.go]: To be honest, this feels complex and error prone. `OpenShiftStatus`/`MicroShiftStatus` and `OpenShiftVersion`/`MicroShiftVersion` are mutually exclusive, and `OKDStatus`/`OKDVersion` would be missing. Maybe you could reuse `OpenShiftStatus`/`OpenShiftVersion` actually, and do something different when pretty-printing depending on the preset.
#3592 only mentions the `Preset` field being wrong, so we have some latitude with these fields.

File: cmd/crc/cmd/status.go [hunk 8]
```diff
@@ -217,6 +225,13 @@ func openshiftStatus(status *status) string {
 	return string(status.OpenShiftStatus)
 }
 
+func microShiftStatus(status *status) string {
+	if status.MicroShiftVersion != "" {
```
Comment (cfergeau) [inline cmd/crc/cmd/status.go]: This is called as 
```
if s.MicroShiftVersion != "" {
		lines = append(lines, line{"MicroShift", microShiftStatus(s)})
}
```
so this test is unneeded. I would change the test above to 
```
if preset == Microshift {
		lines = append(lines, line{"MicroShift", microShiftStatus(s)})
}
```

File: pkg/crc/machine/status.go (hunk 6 above)
Comment (praveenkumar) [reply pkg/crc/machine/status.go:172]: `crc start` wait for cluster operator status, for `oc get nodes` it just wait for API endpoint. so if microshift service is running that means API is already up.

File: cmd/crc/cmd/status.go (hunk 7 above)
Comment (praveenkumar) [reply cmd/crc/cmd/status.go]: it is not only around prettyprint but also json side.

File: cmd/crc/cmd/status.go (hunk 8 above)
Comment (praveenkumar) [reply cmd/crc/cmd/status.go]: yes I didn't change because same what we used for `Openshift` and `podman`, may be another commit to use the preset instead those.

Comment (cfergeau) [reply cmd/crc/cmd/status.go]: well, existing code is buggy, good opportunity to fix it.

File: cmd/crc/cmd/status.go (hunk 7 above)
Comment (cfergeau) [reply cmd/crc/cmd/status.go]: Even on the json side, if `Preset` is correctly set, I don't think we need redundant/mutually exclusive fields.

File: pkg/crc/machine/status.go (hunk 6 above)
Comment (cfergeau) [reply pkg/crc/machine/status.go:172]: I am talking about `crc start` with the microshift preset, which only checks `oc get nodes` (this calls `waitForApiServer`)

File: cmd/crc/cmd/status.go (hunk 7 above)
Comment (gbraad) [reply cmd/crc/cmd/status.go]: Additional fields (or those that change names), ahs to be checked in the receiving end for `undefined` or existence. Which also complicates the receiving end a lot.

File: pkg/crc/api/client/types.go [hunk 9]
```diff
@@ -20,15 +20,17 @@ type StartResult struct {
...
-	DiskSize         int64
-	RAMUse           int64
-	RAMSize          int64
-	Preset           preset.Preset
+	CrcStatus         string
+	OpenshiftStatus   string
+	OpenshiftVersion  string `json:"OpenshiftVersion,omitempty"`
+	MicroShiftStatus  string
+	MicroShiftVersion string `json:"MicroShiftVersion,omitempty"`
+	PodmanVersion     string `json:"PodmanVersion,omitempty"`
```
Comment (gbraad) [inline pkg/crc/api/client/types.go]: This becomes as mess on the receiving end.

Just a `Version` and `Status` will do, as the `Preset` is the key value to determine the meaning

**Review by gbraad — CHANGES_REQUESTED** [review]
This will complicate the logic on both ends and maybe even impede future changes. Each new type of bundle/preset will need new fields?

```json
{
  "success": true,    // <!--- ???
  "crcStatus": "Running",
  "microshiftStatus": "Running",
  "microshiftVersion": "4.12.9",
  ...
  "preset": "microshift"
}
```
could be:

```json
{
  "crcStatus": "Running",
  ...
  "preset": "microshift"
  "status": "Running",
  "version": "4.12.9",
}
```

File: pkg/crc/machine/status.go (hunk 6 above)
Comment (praveenkumar) [reply pkg/crc/machine/status.go:172]: Created a follow up https://github.com/crc-org/crc/issues/3599 on this.

File: cmd/crc/cmd/status.go [hunk 10]
```diff
@@ -180,12 +180,15 @@ func (s *status) prettyPrintTo(writer io.Writer) error {
 		{"CRC VM", s.CrcStatus},
 	}
 
-	if s.OpenShiftVersion != "" {
+	if s.Preset == preset.OpenShift {
 		lines = append(lines, line{"OpenShift", openshiftStatus(s)})
 	}
-	if s.PodmanVersion != "" {
+	if s.Preset == preset.Podman {
```
Comment (cfergeau) [inline cmd/crc/cmd/status.go:186]: With openshift/microshift, we also expose podman, so I think we always want to print this if podman version is set.

File: cmd/crc/cmd/status.go [hunk 11]
```diff
@@ -217,6 +220,13 @@ func openshiftStatus(status *status) string {
 	return string(status.OpenShiftStatus)
 }
 
+func microShiftStatus(status *status) string {
+	if status.Preset == preset.Microshift {
```
Comment (cfergeau) [inline cmd/crc/cmd/status.go]: Shouldn't this be `if status.OpenShiftVersion != ""`? This makes the method identical to `openshiftStatus`?

File: pkg/crc/machine/status.go [hunk 12]
```diff
@@ -57,13 +64,18 @@ func (client *client) Status() (*types.ClusterStatusResult, error) {
...
-	if vm.bundle.IsOpenShift() {
+	switch {
+	case vm.bundle.IsPodman():
+		clusterStatusResult.PodmanVersion = vm.bundle.GetPodmanVersion()
+		clusterStatusResult.Preset = preset.Podman
+	case vm.bundle.IsMicroshift():
+		clusterStatusResult.OpenshiftStatus = getMicroShiftStatus(vm)
+		clusterStatusResult.OpenshiftVersion = vm.bundle.GetOpenshiftVersion()
+		clusterStatusResult.Preset = preset.Microshift
+	default:
```
Comment (cfergeau) [inline pkg/crc/machine/status.go]: The code is starting to get quite repetitive, can you first create a `clusterStatusResult` with with the fields Preset and xxxVersion set. Then you can use this variable in the 2 code paths (cluster is stopped or running) and only set the correct Status  field. This can even be moved to different helpers for improved readabililty.

File: cmd/crc/cmd/status.go (hunk 10 above)
Comment (praveenkumar) [reply cmd/crc/cmd/status.go:186]: @cfergeau I discussed it with @gbraad about the same thing and he don't want to have podman version in case of openshift/microshift preset otherwise some user might think that this cluster running on podman.

Comment (cfergeau) [reply cmd/crc/cmd/status.go:186]: Nobody can know this except you and Gerard. Please split this behaviour change to its own commit with a proper rationale so that it's obvious to everyone that the change is intentional, and why it's being done.

**Comment by praveenkumar** [comment]
> This will complicate the logic on both ends and maybe even impede future changes. Each new type of bundle/preset will need new fields?

This should be now changed.

File: cmd/crc/cmd/status.go [hunk 13]
```diff
@@ -180,10 +180,10 @@ func (s *status) prettyPrintTo(writer io.Writer) error {
 		{"CRC VM", s.CrcStatus},
 	}
 
-	if s.OpenShiftVersion != "" {
+	if s.Preset == preset.OpenShift {
 		lines = append(lines, line{"OpenShift", openshiftStatus(s)})
 	}
-	if s.PodmanVersion != "" {
+	if s.Preset == preset.Podman {
```
Comment (cfergeau) [inline cmd/crc/cmd/status.go:186]: This could become a `switch`.

**Review by cfergeau — APPROVED** [review]
