### PR TITLE
Handle vfkit connection in goroutine to prevent blocking

### LINKED ISSUE #4736: [bug] crc start fail for darwin on nightly run
bundle version: 4.18.2
crc version: 25.04.28+39c193, main branch

Test results: 

- [darwin-amd](https://reportportal-openshiftlocal.apps.dno.ocp-hub.prod.psi.redhat.com/ui/#openshift-local/launches/all/3459?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED)
- [darwin-arm](https://reportportal-openshiftlocal.apps.dno.ocp-hub.prod.psi.redhat.com/ui/#openshift-local/launches/all/3458?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED)

> Step starting CRC with default bundle succeeds: command 'CRC_DISABLE_UPDATE_CHECK=true crc start -p '/Users/podmanqe/crc-e2e/pull-secret' -b /Users/podmanqe/OpenshiftLocal/bundle/openshift/4.18.2/crc_vfkit_4.18.2_arm64.crcbundle', expected to succeed, exited with exit code: 1
Command stdout:
Command stderr: level=debug msg="CRC version: 25.04.28+39c193\n"
level=debug msg="OpenShift version: 4.18.2\n"
level=debug msg="MicroShift version: 4.18.2\n"
level=debug msg="Running 'crc start'"
level=debug msg="Total memory of system is 25769803776 bytes"
level=info msg="Using bundle path /Users/podmanqe/OpenshiftLocal/bundle/openshift/4.18.2/crc_vfkit_4.18.2_arm64.crcbundle"
level=info msg="Checking if running macOS version >= 13.x"
level=debug msg="Running 'sw_vers -productVersion'"
level=debug msg="sw_vers -productVersion is: 15.1"
level=info msg="Checking if running as non-root"
level=info msg="Checking if crc-admin-helper executable is cached"
level=info msg="Checking if running on a supported CPU architecture"
level=debug msg="GOARCH is arm64 GOOS is darwin"
level=info msg="Checking if crc executable symlink exists"
level=info msg="Checking minimum RAM requirements"
level=debug msg="Total memory of system is 25769803776 bytes"
level=info msg="Check if Podman binary exists in: /Users/podmanqe/.crc/bin/oc"
level=info msg="Checking if running emulated on Apple silicon"
level=info msg="Checking if vfkit is installed"
level=info msg="Checking if old launchd config for tray and/or daemon exists"
level=info msg="Checking if crc daemon plist file is present and loaded"
level=debug msg="Running 'bash -c launchctl list | grep com.redhat.crc.daemon | awk '{print $1}''"
level=info msg="Checking SSH port availability"
level=info msg="Loading bundle: crc_vfkit_4.18.2_arm64..."
level=info msg="Starting CRC VM for openshift 4.18.2..."
level=debug msg="Updating CRC VM configuration"
level=debug msg="Running /usr/local/crc/vfkit --cpus 4 --memory 10752 --bootloader efi,variable-store=/Users/podmanqe/.crc/machines/crc/efistore.nvram --device virtio-serial,logFilePath=/Users/podmanqe/.crc/machines/crc/vfkit.log --device virtio-fs,sharedDir=/Users/podmanqe,mountTag=dir0 --device virtio-rng --device virtio-blk,path=/Users/podmanqe/.crc/machines/crc/crc.img --device virtio-net,unixSocketPath=/Users/podmanqe/.crc/crc-unixgram.sock,mac=5a:94:ef:e4:0c:ee --timesync vsockPort=1234"
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="&{4 10752    {[efi variable-store=/Users/podmanqe/.crc/machines/crc/efistore.nvram] true} vsockPort=1234 [virtio-serial,logFilePath=/Users/podmanqe/.crc/machines/crc/vfkit.log virtio-fs,sharedDir=/Users/podmanqe,mountTag=dir0 virtio-rng virtio-blk,path=/Users/podmanqe/.crc/machines/crc/crc.img virtio-net,unixSocketPath=/Users/podmanqe/.crc/crc-unixgram.sock,mac=5a:94:ef:e4:0c:ee] none://  false  {[] false}}""
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="boot parameters: &{EFIVariableStorePath:/Users/podmanqe/.crc/machines/crc/efistore.nvram CreateVariableStore:false}""
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info"
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="virtual machine parameters:""
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="\tvCPUs: 4""
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="\tmemory: 10752 MiB""
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info"
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="Adding virtio-serial device (logFile: /Users/podmanqe/.crc/machines/crc/vfkit.log)""
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="Adding virtio-fs device""
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="Adding virtio-rng device""
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="Adding virtio-blk device (imagePath: /Users/podmanqe/.crc/machines/crc/crc.img)""
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="Adding virtio-net device (nat: false macAddress: [5a:94:ef:e4:0c:ee])""
level=debug msg="time="2025-04-28T03:10:09+02:00" level=info msg="Using unix socket /Users/podmanqe/.crc/crc-unixgram.sock""
level=debug msg="Error: dial unixgram /Users/podmanqe/.crc/vfkit-733d-d608.sock->/Users/podmanqe/.crc/crc-unixgram.sock: connect: connection refused"
level=debug msg="Usage:"
level=debug msg="  vfkit [flags]"
level=debug
level=debug msg="Flags:"
level=debug msg="  -b, --bootloader strings      bootloader configuration (default [])"
level=debug msg="      --cloud-init strings      path to user-data and meta-data cloud-init configuration files (default [])"
level=debug msg="  -c, --cpus uint               number of virtual CPUs (default 1)"
level=debug msg="  -d, --device stringArray      devices"
level=debug msg="      --gui                     display the contents of the virtual machine onto a graphical user interface"
level=debug msg="  -h, --help                    help for vfkit"
level=debug msg="      --ignition string         path to the ignition file"
level=debug msg="  -i, --initrd string           path to the virtual machine initrd"
level=debug msg="  -k, --kernel string           path to the virtual machine Linux kernel"
level=debug msg="  -C, --kernel-cmdline string   Linux kernel command line"
level=debug msg="      --log-level string        set log level"
level=debug msg="  -m, --memory uint             virtual machine RAM size in mibibytes (default 512)"
level=debug msg="      --restful-uri string      URI address for RESTful services (default "none://")"
level=debug msg="  -t, --timesync string         sync guest time when host wakes up from sleep"
level=debug msg="  -v, --version                 version for vfkit"
level=debug
level=debug msg="dial unixgram /Users/podmanqe/.crc/vfkit-733d-d608.sock->/Users/podmanqe/.crc/crc-unixgram.sock: connect: connection refused"
Error starting machine: Error in driver during machine start: exit status 1

### PR DESCRIPTION
**Pull request by vyasgun**
## Description
A bug is being consistently seen where crc is unable to connect to the daemon on restart/recreation. This fix will help prevent seeing this issue.

Fixes: #4736

Relates to: https://github.com/crc-org/crc/pull/4738

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change
- [ ] Chore (non-breaking change which doesn't affect codebase;
  test, version modification, documentation, etc.)

## Contribution Checklist
- [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Which platform have you tested the code changes on? 
    - [ ] Linux
    - [ ] Windows
    - [ ] MacOS

## Summary by Sourcery

Bug Fixes:
- Handle vfkit connections asynchronously to prevent daemon startup from blocking on macOS.

### CODE REVIEW

File: cmd/crc/cmd/daemon_darwin.go [hunk 1]
```diff
@@ -44,8 +44,14 @@ func unixgramListener(vn *virtualnetwork.VirtualNetwork) (*net.UnixConn, error)
...
-	err = vn.AcceptVfkit(context.Background(), vfkitConn)
-	return conn, errors.Wrap(err, "failed to accept vfkit connection")
+	go func() {
+		err := vn.AcceptVfkit(context.Background(), vfkitConn)
+		if err != nil {
+			logging.Errorf("failed to accept vfkit connection: %v", err)
+			return
+		}
+	}()
+	return conn, err
```
Comment (cfergeau) [inline cmd/crc/cmd/daemon_darwin.go:54]: I’m wary of having 2 goroutines running the virtualnetwork code at the same time, I’m really not sure this has been done before and I’m worried of race conditions. Nothing specific to address here, just worries :)
Could you try something like this to see if this helps to shut down the first connection when a second one is created?
```
diff --git a/cmd/crc/cmd/daemon.go b/cmd/crc/cmd/daemon.go
index 82aa5179e..2c2c93799 100644
--- a/cmd/crc/cmd/daemon.go
+++ b/cmd/crc/cmd/daemon.go
@@ -209,11 +209,18 @@ func run(configuration *types.Configuration) error {
        }()
 
        go func() {
+               oldConn := net.Conn(nil)
                for {
-                       _, err := unixgramListener(vn)
+                       conn, err := unixgramListener(vn)
                        if err != nil && !errors.Is(err, net.ErrClosed) {
                                logging.Errorf("unixgramListener error: %v", err)
                        }
+                       log.Warnf("created new vfkit connection: %p", conn)
+                       if oldConn != nil {
+                               log.Warnf("closing old vfkit connection: %p", oldConn)
+                               oldConn.Close()
+                       }
+                       oldConn = conn
                        time.Sleep(1 * time.Second)
                }
        }()
diff --git a/cmd/crc/cmd/daemon_darwin.go b/cmd/crc/cmd/daemon_darwin.go
index 1b5a872dc..bb6dbda86 100644
--- a/cmd/crc/cmd/daemon_darwin.go
+++ b/cmd/crc/cmd/daemon_darwin.go
@@ -50,6 +50,7 @@ func unixgramListener(vn *virtualnetwork.VirtualNetwork) (*net.UnixConn, error)
                        logging.Errorf("failed to accept vfkit connection")
                        return
                }
+               logging.Warnf("end of AcceptVfkit coroutine")
        }()
        return conn, err
 }
```

Comment (cfergeau) [reply cmd/crc/cmd/daemon_darwin.go:54]: After writing this comment, I noticed `err := vn.AcceptVfkit(context.Background(), vfkitConn)`, it has a `context` arg, which are exactly meant to be able to cancel what this function is doing when we need to, see https://pkg.go.dev/context#WithCancel for example. gvisor-tap-vsock code is already watching `ctx.Done()` for cancellations (see `rxNonStream`)

Comment (vyasgun) [reply cmd/crc/cmd/daemon_darwin.go:54]: I added a cancellation context to `vn.AcceptVfkit`. Also added a `connection.Close()` to the goroutine to prevent any leaks.

**Comment by praveenkumar** [comment]
<s>With this change, now it is stuck during fresh start also. Following is logs from daemon, looks like connection is closed.
```
 - - [15/May/2025:10:51:11 +0530] "GET /network/services/forwarder/all HTTP/1.1" 200 3
 - - [15/May/2025:10:51:11 +0530] "GET /network/services/forwarder/all HTTP/1.1" 200 3
 - - [15/May/2025:10:51:11 +0530] "POST /network/services/forwarder/expose HTTP/1.1" 200 0
 - - [15/May/2025:10:51:11 +0530] "POST /network/services/forwarder/expose HTTP/1.1" 200 0
 - - [15/May/2025:10:51:11 +0530] "POST /network/services/forwarder/expose HTTP/1.1" 200 0
 - - [15/May/2025:10:51:11 +0530] "POST /network/services/forwarder/expose HTTP/1.1" 200 0
 - - [15/May/2025:10:51:11 +0530] "POST /network/services/forwarder/expose HTTP/1.1" 200 0
DEBU new connection from /Users/prkumar/.crc/vfkit-354d-1254.sock to /Users/prkumar/.crc/crc-unixgram.sock 
ERRO cannot receive packets from /Users/prkumar/.crc/vfkit-354d-1254.sock, disconnecting: cannot read size from socket: read unixgram /Users/prkumar/.crc/crc-unixgram.sock: use of closed network connection 
ERRO failed to accept vfkit connection: cannot read size from socket: read unixgram /Users/prkumar/.crc/crc-unixgram.sock: use of closed network connection 
INFO listening on /Users/prkumar/.crc/crc-unixgram.sock 
0B sent to the VM, 0B received from the VM
2025/05/15 10:51:15 tcpproxy: for incoming conn 127.0.0.1:52729, error dialing "192.168.127.2:22": connect tcp 192.168.127.2:22: no route to host
0B sent to the VM, 0B received from the VM
```
</s>

Edit: I had some local changes also during testing and after removing those it is working as expected. will wait for @cfergeau for approval and then  merge it.

File: cmd/crc/cmd/daemon_darwin.go [hunk 2]
```diff
@@ -39,13 +44,24 @@ func unixgramListener(vn *virtualnetwork.VirtualNetwork) (*net.UnixConn, error)
...
 	vfkitConn, err := transport.AcceptVfkit(conn)
 	if err != nil {
 		return conn, errors.Wrap(err, "failed to accept vfkit connection")
 	}
-	err = vn.AcceptVfkit(context.Background(), vfkitConn)
-	return conn, errors.Wrap(err, "failed to accept vfkit connection")
+	if cancel != nil {
+		logging.Warnf("new connection to %s. Closing old connection", constants.UnixgramSocketPath)
+		cancel()
+	}
```
Comment (cfergeau) [inline cmd/crc/cmd/daemon_darwin.go]: To avoid the `cancel`/`ctx` global variables, I’d change `unixgramListener` to have an additional return value of type `CancelFunc`. The cancellation can then be handled in the code calling `vsockListener`.
Even if we keep the code as it is currently, I don’t think `ctx` needs to be global, only `cancel`.

And not related to this change, but I wonder if `unixgramListen` would be a better name for this method instead of `unixgramListener` (but just a comment in passing, nothing important)

Comment (vyasgun) [reply cmd/crc/cmd/daemon_darwin.go]: I split the function into two: `setupUnixgramListener` and `handleUnixgramConnection` since `cancel()` needs to be called once the initial connection is established (`transport.AcceptVfkit` returns). The cancellation is now being handled by the caller function.

For the names, what do you think of the two new functions?

**Comment by praveenkumar** [comment]
CI is failing with following error 
```
GOARCH=arm64 GOOS=darwin go build -tags "containers_image_openpgp" -ldflags="-X github.com/crc-org/crc/v2/pkg/crc/version.crcVersion=2.50.0 -X github.com/crc-org/crc/v2/pkg/crc/version.ocpVersion=4.18.2 -X github.com/crc-org/crc/v2/pkg/crc/version.okdVersion=4.15.0-0.okd-2024-02-23-163410 -X github.com/crc-org/crc/v2/pkg/crc/version.microshiftVersion=4.18.2 -X github.com/crc-org/crc/v2/pkg/crc/version.commitSha=32561c " -o out/macos-arm64/crc  ./cmd/crc
GOARCH=amd64 GOOS=darwin go build -tags "containers_image_openpgp" -ldflags="-X github.com/crc-org/crc/v2/pkg/crc/version.crcVersion=2.50.0 -X github.com/crc-org/crc/v2/pkg/crc/version.ocpVersion=4.18.2 -X github.com/crc-org/crc/v2/pkg/crc/version.okdVersion=4.15.0-0.okd-2024-02-23-163410 -X github.com/crc-org/crc/v2/pkg/crc/version.microshiftVersion=4.18.2 -X github.com/crc-org/crc/v2/pkg/crc/version.commitSha=32561c " -o out/macos-amd64/crc  ./cmd/crc
GOOS=linux GOARCH=amd64 go build -tags "containers_image_openpgp" -ldflags="-X github.com/crc-org/crc/v2/pkg/crc/version.crcVersion=2.50.0 -X github.com/crc-org/crc/v2/pkg/crc/version.ocpVersion=4.18.2 -X github.com/crc-org/crc/v2/pkg/crc/version.okdVersion=4.15.0-0.okd-2024-02-23-163410 -X github.com/crc-org/crc/v2/pkg/crc/version.microshiftVersion=4.18.2 -X github.com/crc-org/crc/v2/pkg/crc/version.commitSha=32561c " -o out/linux-amd64/crc  ./cmd/crc
# github.com/crc-org/crc/v2/cmd/crc/cmd
Error: cmd/crc/cmd/daemon.go:216:17: undefined: setupUnixgramListener
Error: cmd/crc/cmd/daemon.go:221:77: undefined: constants.UnixgramSocketPath
Error: cmd/crc/cmd/daemon.go:226:7: undefined: handleUnixgramConnection
```

**Comment by vyasgun** [comment]
@praveenkumar these are due to missing duplicate definitions for other OSes. I will add them

**Comment by praveenkumar** [comment]
> @praveenkumar these are due to missing duplicate definitions for other OSes. I will add them

@vyasgun before push make sure you run `make check` so that you can locally able to find out issue before hitting by CI.

**Comment by vyasgun** [comment]
The failing test `Test OKD bundle` is on Ubuntu 24.04.2 LTS and unrelated to the vfkit changes.

File: cmd/crc/cmd/daemon_darwin.go (hunk 2 above)
Comment (cfergeau) [reply cmd/crc/cmd/daemon_darwin.go]: `cancel` is only required after the initial connection is established, but I don’t think it’s problematic to call it even if it’s not needed?
Good idea to create the context in the caller!

Comment (vyasgun) [reply cmd/crc/cmd/daemon_darwin.go]: I think it's needed every time a new connection is established so that it closes the old connection. It is getting stuck in `vn.AcceptVfkit` implying cancellation will help in cleaning up the old goroutine.
Thank you! 😄

Comment (cfergeau) [reply cmd/crc/cmd/daemon_darwin.go]: I was only (badly) paraphrasing your comment "since cancel() needs to be called once the initial connection is established (transport.AcceptVfkit returns)", but yes, it needs to be called every time.

Comment (vyasgun) [reply cmd/crc/cmd/daemon_darwin.go]: oh okay, by my comment I mean every time a new connection is established. Sorry about the ambiguous language 😓

**Review by cfergeau — APPROVED** [review]

**Comment by gbraad** [comment]
> https://github.com/crc-org/crc/pull/4753#issuecomment-2885793978

And this went wrong. Added, but not tested. Please make sure to update the checklist.

> - [ ] Which platform have you tested the code changes on?
>   - [ ] Windows

This is important to understand what needs to be focussed on. From development, I can see this was NOT tested at all.
