### PR TITLE
hyperv: Replace parseLines/SplitLines with getFirstLine

### LINKED ISSUE #3764: Error for Hyper-V available check when management tools not installed
The line:
https://github.com/crc-org/crc/blob/e43de8dfca711be4f76acef3d07b67ea121cbe1f/pkg/drivers/hyperv/powershell_windows.go#L47

will fail when Management tools aren't installed:

```
INFO Creating CRC VM for OpenShift 4.13.3...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/crc-org/crc/pkg/drivers/hyperv.hypervAvailable()
        /builddir/build/BUILD/crc-2.23.0/pkg/drivers/hyperv/powershell_windows.go:47 +0xb4
github.com/crc-org/crc/pkg/drivers/hyperv.(*Driver).PreCreateCheck(0xc0005edef0)
        /builddir/build/BUILD/crc-2.23.0/pkg/drivers/hyperv/hyperv_windows.go:119 +0x3c
github.com/crc-org/crc/pkg/crc/machine.createHost({{0xc000bb0d9a, 0x17}, {0x2320065, 0x3}, 0x2400, 0x4, 0x1f, {0xc0004f4940, 0x3a}, {0xc000dc1398, ...}, ...}, ...)
        /builddir/build/BUILD/crc-2.23.0/pkg/crc/machine/start.go:723 +0x19c
github.com/crc-org/crc/pkg/crc/machine.(*client).Start(0xc000daa5c0, {0x26cc6d8, 0xc000daad40}, {{0xc000bb0d80, 0x3b}, 0x2400, 0x4, 0x1f, {0x0, 0x0}, ...})
        /builddir/build/BUILD/crc-2.23.0/pkg/crc/machine/start.go:329 +0x9d8
github.com/crc-org/crc/pkg/crc/machine.(*Synchronized).Start(0xc000daa600, {0x26cc780?, 0xc000c805a0?}, {{0xc000bb0d80, 0x3b}, 0x2400, 0x4, 0x1f, {0x0, 0x0}, ...})
        /builddir/build/BUILD/crc-2.23.0/pkg/crc/machine/sync.go:93 +0xca
github.com/crc-org/crc/cmd/crc/cmd.runStart({0x26cc780, 0xc000c805a0})
        /builddir/build/BUILD/crc-2.23.0/cmd/crc/cmd/start.go:111 +0x5ad
github.com/crc-org/crc/cmd/crc/cmd.glob..func11(0x3751c20, {0x5?, 0x2336a0c?, 0xc?})
        /builddir/build/BUILD/crc-2.23.0/cmd/crc/cmd/start.go:57 +0x57
github.com/crc-org/crc/cmd/crc/cmd.executeWithLogging.func1(0x3751c20, {0x3cfc9f0, 0x0, 0x0})
        /builddir/build/BUILD/crc-2.23.0/cmd/crc/cmd/root.go:170 +0x102
github.com/spf13/cobra.(*Command).execute(0x3751c20, {0x3cfc9f0, 0x0, 0x0})
        /builddir/build/BUILD/crc-2.23.0/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x3753600)
        /builddir/build/BUILD/crc-2.23.0/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/crc-2.23.0/vendor/github.com/spf13/cobra/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /builddir/build/BUILD/crc-2.23.0/vendor/github.com/spf13/cobra/command.go:961
github.com/crc-org/crc/cmd/crc/cmd.Execute()
        /builddir/build/BUILD/crc-2.23.0/cmd/crc/cmd/root.go:105 +0xd9
main.main()
        /builddir/build/BUILD/crc-2.23.0/cmd/crc/main.go:8 +0x17
```

### PR DESCRIPTION
**Pull request by cfergeau**
In the hyperv code, there are many occurrences of resp :=
os.SplitLines(stdout) if resp[0] == ...

This does not check if `resp` is empty before trying to reference it, which
recently triggered a panic in crc ( 
https://github.com/crc-org/crc/issues/3764 )

This code adds a `getFirstLine` helper which will return an empty string if
stdout is "".

This should fix https://github.com/crc-org/crc/issues/3764

### CODE REVIEW

File: pkg/crc/cluster/clusteroperator.go [hunk 1]
```diff
@@ -101,7 +102,7 @@ func getStatus(ctx context.Context, lister operatorLister, selector []string) (*
 
 	found := false
 	for _, c := range co.Items {
-		if len(selector) > 0 && !contains(c.ObjectMeta.Name, selector) {
+		if len(selector) > 0 && !crcos.Contains(selector, c.ObjectMeta.Name) {
```
Comment (gbraad) [inline pkg/crc/cluster/clusteroperator.go]: Why do we invert the selector and name?

File: pkg/drivers/hyperv/powershell_windows.go [hunk 2]
```diff
@@ -26,15 +25,13 @@ func cmd(args ...string) error {
 	return err
 }
 
-func parseLines(stdout string) []string {
-	resp := []string{}
-
-	s := bufio.NewScanner(strings.NewReader(stdout))
-	for s.Scan() {
-		resp = append(resp, s.Text())
+func getFirstLine(stdout string) string {
```
Comment (gbraad) [inline pkg/drivers/hyperv/powershell_windows.go]: Not part of the util.go ?

File: pkg/os/util.go [hunk 3]
```diff
@@ -113,3 +114,24 @@ func RemoveFileIfExists(path string) error {
 func RunningUsingSSH() bool {
 	return os.Getenv("SSH_TTY") != ""
 }
+
+// Split a multi line string in an array of string, one for each line
+func SplitLines(input string) []string {
```
Comment (gbraad) [inline pkg/os/util.go]: why is this part of crcos (operating system-specific code). this looks like generic line/string manipulation

File: pkg/drivers/hyperv/powershell_windows.go (hunk 2 above)
Comment (cfergeau) [reply pkg/drivers/hyperv/powershell_windows.go]: This package is the only user of `getFirstLine` so I kept it there as it's a bit specialized.

File: pkg/crc/cluster/clusteroperator.go (hunk 1 above)
Comment (cfergeau) [reply pkg/crc/cluster/clusteroperator.go]: The function prototype in `clusteroperator.go` was `func contains(value string, list []string) bool`, the new helper is ` Contains(s []string, e string) bool`

File: pkg/drivers/hyperv/powershell_windows.go (hunk 2 above)
Comment (gbraad) [reply pkg/drivers/hyperv/powershell_windows.go]: the issue in question was the only place for `resp[0]`, for which we also use the `| get-unique` operator in powershell. I don't mind, but found it very generic.

File: pkg/os/util.go (hunk 3 above)
Comment (cfergeau) [reply pkg/os/util.go]: I could not find a more appropriate package, and was not sure adding a `strings` package for 2 functions was worh it. I can make this change if you prefer.

Comment (gbraad) [reply pkg/os/util.go]: I think adding a strings make sense, as I might even think adding the firstline justifies the use. it makes it clearer in intent. perhaps we might even add a getlastline at some point ;-)

File: pkg/crc/services/dns/dns_windows.go [hunk 4]
```diff
@@ -30,7 +29,7 @@ func runPostStartForOS(serviceConfig services.ServicePostStartConfig) error {
 
 	time.Sleep(2 * time.Second)
 
-	if !contains(getInterfaceNameserverValues(networkInterface), serviceConfig.IP) {
+	if !crcos.Contains(getInterfaceNameserverValues(networkInterface), serviceConfig.IP) {
```
Comment (gbraad) [inline pkg/crc/services/dns/dns_windows.go]: then is this not in error?

```
if !crcos.Contains(getInterfaceNameserverValues(networkInterface), serviceConfig.IP) {
```

the order for the parameters have changed? https://github.com/crc-org/crc/pull/3765/files#r1270651088 Let's stay consistent.

File: pkg/crc/cluster/clusteroperator.go (hunk 1 above)
Comment (gbraad) [reply pkg/crc/cluster/clusteroperator.go]: Thanks for confirming, which means the order has changed. Using more clear variables on the function might make this clearer; `s` is `strings`, and `e` is expected?

This is not the only usage: https://github.com/crc-org/crc/pull/3765/files#r1270660861

File: pkg/crc/services/dns/dns_windows.go (hunk 4 above)
Comment (cfergeau) [reply pkg/crc/services/dns/dns_windows.go]: `dns_windows.go` was using `contains(s []string, e string) bool` and `clusteroperator.go` used `contains(value string, list []string) bool`,  so the order will change in one of the instances.

Comment (gbraad) [reply pkg/crc/services/dns/dns_windows.go]: Check

Can we in that case also more clearly describe the parameters:

```
func Contains(s []string, e string) bool {
```

with actual 'words' instead of abbreviated identifiers. https://github.com/crc-org/crc/pull/3765#discussion_r1270661563

`s` = `strings` and `e` = `expected`?

File: pkg/drivers/hyperv/powershell_windows.go (hunk 2 above)
Comment (cfergeau) [reply pkg/drivers/hyperv/powershell_windows.go]: ok I moved it.

File: pkg/os/util.go (hunk 3 above)
Comment (cfergeau) [reply pkg/os/util.go]: Done.

File: pkg/strings/strings.go [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+
+	s := bufio.NewScanner(strings.NewReader(input))
+	for s.Scan() {
+		output = append(output, s.Text())
+	}
+
+	return output
+}
+
+func FirstLine(stdout string) string {
```
Comment (gbraad) [inline pkg/strings/strings.go]: `s/stdOut/input/`, just like in `SplitLines`. `stdOut` does not have any meaning here, except from the caller.

File: pkg/strings/strings.go [hunk 6]
```diff
@@ -0,0 +1,36 @@
+package strings
+
+import (
+	"bufio"
+	"strings"
+)
+
+func Contains(s []string, e string) bool {
```
Comment (gbraad) [inline pkg/strings/strings.go]: `s/s/strings/`, `s/e/expected/` or `compare`. other functions use more descriptive parameters, like `input`.

**Review by gbraad — CHANGES_REQUESTED** [review]
parameters are not clear/consistent.

otherwise lgtm

File: pkg/strings/strings.go (hunk 6 above)
Comment (cfergeau) [reply pkg/strings/strings.go]: I used needle/haystack, I can change again if this is harder to read than it should.

**Comment by cfergeau** [comment]
Let's hold this for a little bit, I'll add some unit tests.

**Comment by cfergeau** [comment]
I've now added unit tests, and they made me wonder if it would not be best to change `SplitLines("")` to return `{ "" }` instead of `{ }`, as at the moment it's a bit weird that `SplitLines("a\n")` returns `{ "a" }`, `SplitLines("a")` also returns `{ "a" }`, but we don't have the same behaviour if we use an empty string instead of `"a"`

**Comment by gbraad** [comment]
why haystack and needle? stay consistent with the rest and use `input` and somehing like `match`. As in a `findNeedle`-like function I expect the identifier to be returned of the `needle` that matches, not just a `bool`-value.

File: pkg/strings/strings.go [hunk 7]
```diff
@@ -0,0 +1,36 @@
+package strings
+
+import (
+	"bufio"
+	"strings"
+)
+
+func Contains(haystack []string, needle string) bool {
```
Comment (gbraad) [inline pkg/strings/strings.go]: inconsistent with other naming; also, this does not work like a `FindNeedle`-function.

**Review by gbraad — CHANGES_REQUESTED** [review]

**Comment by anjannath** [comment]
> I've now added unit tests, and they made me wonder if it would not be best to change `SplitLines("")` to return `{ "" }` instead of `{ }`, as at the moment it's a bit weird that `SplitLines("a\n")` returns `{ "a" }`, `SplitLines("a")` also returns `{ "a" }`, but we don't have the same behaviour if we use an empty string instead of `"a"`

with just `"\n"` its an empty line but with `""` there's no line, so maybe not returning `{ "" }` is better or we could decide to treat empty lines as no line and return `{}` for `"\n"` this will make it consistent

**Review by gbraad — APPROVED** [review]

**Comment by cfergeau** [comment]
> > I've now added unit tests, and they made me wonder if it would not be best to change `SplitLines("")` to return `{ "" }` instead of `{ }`, as at the moment it's a bit weird that `SplitLines("a\n")` returns `{ "a" }`, `SplitLines("a")` also returns `{ "a" }`, but we don't have the same behaviour if we use an empty string instead of `"a"`
> 
> with just `"\n"` its an empty line but with `""` there's no line, so maybe not returning `{ "" }` is better or we could decide to treat empty lines as no line and return `{}` for `"\n"` this will make it consistent

The initial bug is that `{}` is not handled correctly by our code, if we never return `{}`, there is no bug :)
`{}` for `"\n'` would not be that consistent, as `"\n\n"` returns `{ "", ""}`

**Review by anjannath — APPROVED** [review]
