### PR TITLE
start.go: Set chronyd in manual mode

### LINKED ISSUE #4337: Certificate rotation test failed
CRC 2.41.0 release test, the Certificate rotation test failed. (only tested on RHEL)
> level=debug msg="retry loop: attempt 29"
06:17:38.421500  stderr: level=debug msg="Running SSH command: timeout 5s oc get csr --context admin --cluster crc --kubeconfig /opt/kubeconfig"
06:17:38.544459  stderr: level=debug msg="SSH command results: err: Process exited with status 1, output: "
06:17:38.544489  stderr: level=debug msg="E0928 06:17:38.155424    9910 memcache.go:265] couldn't get current server API group list: Get \"https://api.crc.testing:6443/api?timeout=32s\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-09-28T06:17:38Z is after 2025-08-19T06:02:04Z\nE0928 06:17:38.158515    9910 memcache.go:265] couldn't get current server API group list: Get \"https://api.crc.testing:6443/api?timeout=32s\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-09-28T06:17:38Z is after 2025-08-19T06:02:04Z\nE0928 06:17:38.161173    9910 memcache.go:265] couldn't get current server API group list: Get \"https://api.crc.testing:6443/api?timeout=32s\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-09-28T06:17:38Z is after 2025-08-19T06:02:04Z\nE0928 06:17:38.164017    9910 memcache.go:265] couldn't get current server API group list: Get \"https://api.crc.testing:6443/api?timeout=32s\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-09-28T06:17:38Z is after 2025-08-19T06:02:04Z\nE0928 06:17:38.166502    9910 memcache.go:265] couldn't get current server API group list: Get \"https://api.crc.testing:6443/api?timeout=32s\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-09-28T06:17:38Z is after 2025-08-19T06:02:04Z\nUnable to connect to the server: tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-09-28T06:17:38Z is after 2025-08-19T06:02:04Z\n"
06:17:38.544501  stderr: level=debug msg="error: Temporary error: ssh command error:\ncommand : timeout 5s oc get csr --context admin --cluster crc --kubeconfig /opt/kubeconfig\nerr     : Process exited with status 1\n - sleeping 1s"

log link: https://crcqe-asia.s3.ap-south-1.amazonaws.com/release/2.41.0/ocp/rhel-x86-9.4/qe-results/e2e_2024-8-28_05-41-04.log

### PR DESCRIPTION
**Pull request by praveenkumar**
From 4.17 kubelet-dependency.target have chrony-wait-service as dependency which start the chrony service again in the VM and set the time back to normal which cause no cert rotation for cluster and test are failing.

This PR set the chrony conf to manual which prevent to update the VM time even restart of chronyd service.

Fixes: #4337 

Dependency: https://github.com/crc-org/snc/pull/1016

To test this try following
```
$ crc setup  -b https://storage.googleapis.com/crc-bundle/crc_libvirt_4.19.0-ec.2_amd64_1016.crcbundle
$ sudo timedatectl set-ntp off
$ sudo date -s '13 month'
$ CRC_DEBUG_ENABLE_STOP_NTP=true  ./crc start -b https://storage.googleapis.com/crc-bundle/crc_libvirt_4.19.0-ec.2_amd64_1016.crcbundle --log-level debug
```

### CODE REVIEW

File: pkg/crc/machine/start.go [hunk 1]
```diff
@@ -440,6 +440,9 @@ func (client *client) Start(ctx context.Context, startConfig types.StartConfig)
 		if _, _, err := sshRunner.RunPrivileged("Turning off the ntp server", "timedatectl set-ntp off"); err != nil {
 			return nil, errors.Wrap(err, "Failed to stop network time synchronization")
 		}
+		if _, _, err := sshRunner.RunPrivileged("Manual mode for chrony config", "tee /etc/chrony.conf <<< \"manual\""); err != nil {
```
Comment (albfan) [inline pkg/crc/machine/start.go:443]: Should we keep original config and revert it on test finished?

Comment (albfan) [reply pkg/crc/machine/start.go:443]: this is on vm so no need to revert

**Review by albfan — APPROVED** [review]
