### PR TITLE
don't try to get IP of VM when its not running

### LINKED ISSUE #4512: [BUG] `crc status` for a stopped instance on Linux returns `Error getting ip: host is not running`
### General information

Running on Fedora 41, crc status sometimes fail with this error

### Operating System

Linux

### Hypervisor

KVM

### Did you run `crc setup` before `crc start`?

yes

### Running on

Laptop

### Steps to reproduce

1. crc setup
2. crc start
4. crc stop
5. crc status

### CRC version

```shell
CRC version: 2.45.0+7aeb3b
OpenShift version: 4.17.7
MicroShift version: 4.17.7
```

### CRC status

```shell
CRC VM:          Stopped
OpenShift:       Stopped (v4.17.7)
RAM Usage:       0B of 0B
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     25.71GB
Cache Directory: /home/alberto/.crc/cache
```

### CRC config

```shell
Modifies crc configuration properties.
Properties: 

* bundle                                     Bundle path/URI - absolute or local path, http, https or docker URI (string, like 'https://foo.com/crc_libvirt_4.17.7_amd64.crcbundle', 'docker://quay.io/myorg/crc_libvirt_4.17.7_amd64.crcbundle:2.45.0' default '/home/alberto/.crc/cache/crc_libvirt_4.17.7_amd64.crcbundle' )
* consent-telemetry                          Consent to collection of anonymous usage data (yes/no)
* cpus                                       Number of CPU cores (must be greater than or equal to '4')
* disable-update-check                       Disable update check (true/false, default: false)
* disk-size                                  Total size in GiB of the disk (must be greater than or equal to '31')
* enable-bundle-quay-fallback                If bundle download from the default location fails, fallback to quay.io (true/false, default: false)
* enable-cluster-monitoring                  Enable cluster monitoring Operator (true/false, default: false)
* enable-emergency-login                     Enable emergency login for 'core' user. Password is randomly generated. (true/false, default: false)
* enable-experimental-features               Enable experimental features (true/false, default: false)
* enable-shared-dirs                         Mounts host's home directory at '/' in the CRC VM (true/false, default: true)
* host-network-access                        Allow TCP/IP connections from the CRC VM to services running on the host (true/false, default: false)
* http-proxy                                 HTTP proxy URL (string, like 'http://my-proxy.com:8443')
* https-proxy                                HTTPS proxy URL (string, like 'https://my-proxy.com:8443')
* ingress-http-port                          HTTP port to use for OpenShift ingress/routes on the host (1024-65535, default: 80)
* ingress-https-port                         HTTPS port to use for OpenShift ingress/routes on the host (1024-65535, default: 443)
* kubeadmin-password                         User defined kubeadmin password
* memory                                     Memory size in MiB (must be greater than or equal to '10752')
* nameserver                                 IPv4 address of nameserver (string, like '1.1.1.1 or 8.8.8.8')
* network-mode                               Network mode (user or system)
* no-proxy                                   Hosts, ipv4 addresses or CIDR which do not use a proxy (string, comma-separated list such as '127.0.0.1,192.168.100.1/24')
* persistent-volume-size                     Total size in GiB of the persistent volume used by the CSI driver for microshift preset (must be greater than or equal to '15')
* preset                                     Virtual machine preset (valid values are: [openshift okd microshift])
* proxy-ca-file                              Path to an HTTPS proxy certificate authority (CA)
* pull-secret-file                           Path of image pull secret (download from https://console.redhat.com/openshift/create/local)
* skip-check-admin-helper-cached             Skip preflight check (true/false, default: false)
* skip-check-bundle-extracted                Skip preflight check (true/false, default: false)
* skip-check-crc-network                     Skip preflight check (true/false, default: false)
* skip-check-crc-network-active              Skip preflight check (true/false, default: false)
* skip-check-crc-symlink                     Skip preflight check (true/false, default: false)
* skip-check-daemon-systemd-sockets          Skip preflight check (true/false, default: false)
* skip-check-daemon-systemd-unit             Skip preflight check (true/false, default: false)
* skip-check-dnsmasq-network-manager-config  Skip preflight check (true/false, default: false)
* skip-check-kvm-enabled                     Skip preflight check (true/false, default: false)
* skip-check-libvirt-driver                  Skip preflight check (true/false, default: false)
* skip-check-libvirt-group-active            Skip preflight check (true/false, default: false)
* skip-check-libvirt-installed               Skip preflight check (true/false, default: false)
* skip-check-libvirt-running                 Skip preflight check (true/false, default: false)
* skip-check-libvirt-version                 Skip preflight check (true/false, default: false)
* skip-check-network-manager-dispatcher-file Skip preflight check (true/false, default: false)
* skip-check-network-manager-installed       Skip preflight check (true/false, default: false)
* skip-check-network-manager-running         Skip preflight check (true/false, default: false)
* skip-check-podman-in-ocbindir              Skip preflight check (true/false, default: false)
* skip-check-ram                             Skip preflight check (true/false, default: false)
* skip-check-root-user                       Skip preflight check (true/false, default: false)
* skip-check-supported-cpu-arch              Skip preflight check (true/false, default: false)
* skip-check-systemd-networkd-running        Skip preflight check (true/false, default: false)
* skip-check-systemd-resolved-running        Skip preflight check (true/false, default: false)
* skip-check-user-in-libvirt-group           Skip preflight check (true/false, default: false)
* skip-check-virt-enabled                    Skip preflight check (true/false, default: false)
* skip-check-vsock                           Skip preflight check (true/false, default: false)
* skip-check-wsl2                            Skip preflight check (true/false, default: false)

Usage:
  crc config SUBCOMMAND [flags]
  crc config [command]

Available Commands:
  get         Get a crc configuration property
  set         Set a crc configuration property
  unset       Unset a crc configuration property
  view        Display all assigned crc configuration properties

Flags:
  -h, --help   help for config

Global Flags:
      --log-level string   log level (e.g. "debug | info | warn | error") (default "info")

Use "crc config [command] --help" for more information about a command.
```

### Host Operating System

```shell
NAME="Fedora Linux"
VERSION="41 (Workstation Edition)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=41
VERSION_CODENAME=""
PLATFORM_ID="platform:f41"
PRETTY_NAME="Fedora Linux 41 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:41"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f41/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=41
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=41
SUPPORT_END=2025-12-15
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Expected behavior

crc status shows correctly

### Actual behavior

CRC version: 2.45.0+7aeb3b
OpenShift version: 4.17.7
MicroShift version: 4.17.7
Running 'crc status'
Error getting ip: host is not running

### CRC Logs

```shell
11:43:23.730206    bash: crc stop
11:43:23.793817  stderr: level=debug msg="CRC version: 2.45.0+7aeb3b\n"
11:43:23.793864  stderr: level=debug msg="OpenShift version: 4.17.7\n"
11:43:23.793874  stderr: level=debug msg="MicroShift version: 4.17.7\n"
11:43:23.793881  stderr: level=debug msg="Running 'crc stop'"
11:43:23.793935  stderr: level=debug msg="Checking file: /home/fedora/.crc/machines/crc/.crc-exist"
11:43:23.794066  stderr: level=debug msg="Checking file: /home/fedora/.crc/machines/crc/.crc-exist"
11:43:23.794275  stderr: level=debug msg="Found binary path at /home/fedora/.crc/bin/crc-driver-libvirt-amd64"
11:43:23.794421  stderr: level=debug msg="Launching plugin server for driver libvirt"
11:43:23.825018  stderr: level=debug msg="Plugin server listening at address 127.0.0.1:45913"
11:43:23.825892  stderr: level=debug msg="() Calling .GetVersion"
11:43:23.827041  stderr: level=debug msg="Using API Version 1"
11:43:23.827071  stderr: level=debug msg="() Calling .SetConfigRaw"
11:43:23.827506  stderr: level=debug msg="() Calling .GetMachineName"
11:43:23.827720  stderr: level=debug msg="(crc) Calling .GetBundleName"
11:43:23.828522  stderr: level=debug msg="(crc) Calling .GetState"
11:43:23.828847  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:23Z\" level=debug msg=\"Getting current state...\""
11:43:23.828884  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:23Z\" level=debug msg=\"Fetching VM...\""
11:43:23.855018  stderr: level=debug msg="Making call to close driver server"
11:43:23.855048  stderr: level=debug msg="(crc) Calling .Close"
11:43:23.855237  stderr: level=debug msg="Successfully made call to close driver server"
11:43:23.855250  stderr: level=debug msg="Making call to close connection to plugin binary"
11:43:23.855290  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:23Z\" level=debug msg=\"Closing plugin on server side\""
11:43:23.855462  stderr: level=debug msg="Checking file: /home/fedora/.crc/machines/crc/.crc-exist"
11:43:23.855598  stderr: level=debug msg="Found binary path at /home/fedora/.crc/bin/crc-driver-libvirt-amd64"
11:43:23.855674  stderr: level=debug msg="Launching plugin server for driver libvirt"
11:43:23.885131  stderr: level=debug msg="Plugin server listening at address 127.0.0.1:36633"
11:43:23.886026  stderr: level=debug msg="() Calling .GetVersion"
11:43:23.886583  stderr: level=debug msg="Using API Version 1"
11:43:23.886626  stderr: level=debug msg="() Calling .SetConfigRaw"
11:43:23.887458  stderr: level=debug msg="() Calling .GetMachineName"
11:43:23.888123  stderr: level=debug msg="(crc) Calling .GetBundleName"
11:43:23.888850  stderr: level=info msg="Stopping kubelet and all containers..."
11:43:23.888879  stderr: level=debug msg="(crc) Calling .GetIP"
11:43:23.889180  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:23Z\" level=debug msg=\"GetIP called for crc\""
11:43:23.889230  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:23Z\" level=debug msg=\"Getting current state...\""
11:43:23.889259  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:23Z\" level=debug msg=\"Fetching VM...\""
11:43:23.913956  stderr: level=debug msg="Using root access: Executing systemctl stop kubelet"
11:43:23.913986  stderr: level=debug msg="Running SSH command: sudo systemctl stop kubelet"
11:43:23.913996  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:23Z\" level=debug msg=\"IP address: 192.168.130.11\""
11:43:23.933667  stderr: level=debug msg="Using ssh private keys: [/home/fedora/.crc/machines/crc/id_ed25519 /home/fedora/.crc/cache/crc_libvirt_4.17.7_amd64/id_ecdsa_crc]"
11:43:24.254927  stderr: level=debug msg="SSH command results: err: <nil>, output: "
11:43:24.254962  stderr: level=debug msg="Using root access: stopping all containers"
11:43:24.254971  stderr: level=debug msg="Running SSH command: sudo -- sh -c 'crictl stop $(crictl ps -q)'"
11:43:33.863730  stderr: level=debug msg="SSH command results: err: Process exited with status 1, output: 6f6910e200157688cc15d37afbdaf42f262575ae82e7c542c68c2671e3a00d3e\n4b6a3283efbe77887d86537822a7aebb6ed286aedfbdb49691fab1aeaadd105b\nf6bbe2177b03b408c6516f329015a94672bbf8c0e8578702265c82689d9e29cf\n769ce0ff212501b0ff4c1fc804db1bb83638c8ba704574e6209d25f4bc9220c8\n1c7d3aea8d277604350333732d2845bc6b6f2807fc01af0a1eedcc830caad60b\n1b5841f1e00533b577c895b592db3e1992bb59f5285d5db0f8954c25d9b4bf0d\n16b28f044b84724af836a69a80f7f369f4d7ef998b7c4d2608a177426b40d68d\n5c01308e77e4234354531b1f111d42755edd6c138db61766efc9776e5167fb9a\n490d38f49887bf84ef03a9303262bae97ec38aba489158dfd5b006079b951ce1\nf8349404c55522d602d8608dd5c8754ac0dd4dd7ed61b01a425f2f0e11551881\nfdefe6b98f9941b9c048fb74d276845c654d854d76eb8453591398f8f42d4e8d\nfefec32cfe6892590135564ed5c295877d7f35d5caddf4c68ed10b06911c626c\nb3d3ab3ccb694e87895d5203bab13aa3c024055a7e377f3f8fa08862e90d02cf\n4a8b392cc94cf7a4c65ae2378ca43b039b78f4c0778804998ba9d68d3ef6c6c3\nd3e748d5eda4c2d6c66924c94d4b6d42f9631c273f62d49edd4f0375a78b98b5\n4fc57b1a2eabec99fa8c2045efc24d618d545795192562c9cbfea93b6f4493f4\n35b8bc573c1638522ff73938eb1fd466d10a5b81eff09bc4dc72c7b415f8b264\nc72efce2ed139218152f2ef376b39fded25d58b965beead7b378e68b275d5b00\n1c2bb15358280d35dc645be13e657febcd1c797a169cd2bd1eb1a7067437b8db\n629ef95ce275a032051691808b6f179b60e7a3a05b6a31b97eb1de47076607ac\naf556491e9f5849418c38cbec9fa6ea6350eba8e0a3cfb6d50df5a36d0cb65e6\n21cb467f3aea5226095daa11b5e125d01aec5ab40306913d3f713650d174a144\nef23894cb79da89f12cf9c09865d8e42e682265e571006f98730b6e2b96c406c\n861cd4675849bae9982950d70943adc7ce9b0ce08f522499532d1faa3bdf7ea3\n6adf6fd583542c799002906766aa793687be200cfea0d80e5c51832c70599aaf\na0f3e7fcf26d039231fbd04737c00b68bef965008420be9868a9db088130795e\n774af2c640eb2420ae006d7c429ff9b30fc18b4d3dc122c81b4a92d0bae8f8d2\n8eadbc2c5617b367893b4ccfe59875383b23632765716040f4e6cc6e496ae1e1\n9e5fd6c804122c28c6b0a74d95781132f1415ba9b762727207d188156cf57bff\nf399a0f1b480604c856d689d04e9e276d044069967051d61edd32a7b5d173f15\ncccf8fcff2c57ed79d540c88d0700a124caab0bb161e0e8d3bb2012efe04e7f5\na1b6184f4bb7ba14d79dbf935f1d0520c2212a32cb8570089d35ec61ab1a1829\nd483d47ddf7aa21027d2af92e8bed515d89a0fc166c002e3980d3158f889346a\n60776a9f95c9635f0599c5b503b59a566b3a11330d45fdb0cdd65a3a1cee313f\n1c535ce10a95291623a773f40bf9499f409f6e909a66287be0187c846e0c2019\n9345570dd7a4753b9d0cd0af52cf3992e9aace11e104c0fa3c70ebf33cc4bd9e\n5e200ccaf8ed5590aee108688f567693602c0973819d5a2584bb1a0ea9b16518\n9db260752da9a20a6cd72071a927a682fb3f9b26768fdda8fd7fdb7f27813fd3\n71173b0917f6fb6d401a9d12d23acea870e4279b443bcd6e8785bb7da06e685c\n15d6f4604e71d25d7a2e3068fb88757eb80b7e3bdf03d5e9b8c84926ad02cc3d\n1877cdaa6727a8c98a5fce945dfffe1806b1401bd24a7278d5cdd5c42ceae228\n34d7811efcbc8e60f1ae71fec1f69865280484508b16d4ea1c5491827af38b3e\naba9b21035660048b635399b497c062e8f0d9d5d8704d0c8bfa61c862df57dc6\nf4e8edfaa3e2f93db7da94a2e5a56e55058f3ff204ff0e4591f75d9f0aea6835\ncbfe763ed4e4a9e3f0658ec9352f9a8134118273e8f32ca4562f7189f988f7da\nb597a1369790b9ebb932ba74bf0f539ca296b89f5d8487eb5f0d4f909324fb87\ncc2db343fb95091a4dbc829cbad6e730e8dbe318add2507f2c30f3d43e8d525e\n4fb46e990c6a280437f08f2d9677aae934a41ca158cefd791d14b9db53482f8c\n00c08ffaef0062bc7c1d2ee9f1d0d28015ae771841b3ab0fd657a4c797ee278c\n55a24d35d456fe3b79ab398261d8116629c52892da89fb842d8c263c4cc827dc\n245eed7314a29008f4c421e4a6d9071bfeb0b83ea3a316ec93bc85af8669daa9\n901219e179b1552705ce997198d2093e7b4cd8ce0b45631c09c243577e5f05fb\n3c2704b84e199a59b7196e2d843bdc0bb9492651ae6e433260362e7677037818\nffa05d087513aca4f63d77f674d847de17c3ddbb7f33db55560240d39d9b361a\n303172af8d5a29637594cc9a284f1c66943ca81483ef80075a837cc574f8e5d3\nf3b2d3ff9946144bb49451bf97d591da13ee07726088dfca8fe1d135fc51ffc1\nbdad7563116bec34a92775f40edfe9cb2d3319e39ccee538bde1f0d91635be80\n78282daf64993ea84eb3fa7016c423960493b0e382fc724c8c65a301241508cf\n54e13a4b9d6bb533f16dc771f608fdeab801b851b3f348083d8d5f4eb6723eb0\nbae6e462d63d302aec1cd834509585048f0e8e74006e069c376ef5d389525577\ne23d1892a7ff391463a75e55eaaeac2f3ac97b6f857e1960e0f8fe3ba3889786\n5ba22636b93b3b1c5bd13040d778ecbadca65889cf514ad22ece1375bcc6a296\n31ffd4479cc9697419b477eea5a9d0152909f702d9f46c2c8e57fa547fab8907\n89c47b42bfde7c101b3b3210ec558d5b05c472e1c03ddd53908786697396b054\n442e873d6efaf5986987160910f6e957db2824867f2652a649c4a566b495e627\n1736e5501f4e96592b3bdd5c10e84680a4cc6e3d7c3ff6ca366b905f9f3a732f\n6c9648a3b63c1b505fadd71b7b7dc4bfd00b41bb9113cef7cb470dcb755556f0\ne75409afb1ea6266c038e83cb01ff00ced7628e295721a18ba08a3a1df5cb35e\nd927f7d95b4550feb7ff7fe96dd8f32dfec55240e52a12ce2594cea463c03496\nbab882bd99f3fc4c50a02267d7633f0799e075af026476d837253ccb6fde339e\nd7a8f147b1eb8773e35e4b5697a2cd57523496485fd07bf3a829ddc1041f82bf\n3a288b0d172bf12d903189453c7c186c22c6284c31d0232c261a6121a115c1ba\n120c1090ca0cb2d7abd5a561b054c194a5ff4bf36ec2ab7a0a8a659cc6e6e87b\n707a9e45397c88afeba3a82d8816af21af38cb9e7ea8fe64f38fb665c4ee8750\n752fd1b9546cac0110a8e654a18cc4d118f3f195597a00a881a4e145d9de3e7d\nd3338b875468972d23f8d77811504c97375d9f0d450e3ddfe1a1ce6a388e2482\ne3b29caf9c1de5ecaea83b390730b6239c38a2332d28188eccf77c8afd145d76\n8b44ade3a9f858b240eec9e8460c2450d000b422de468a832769080b016d81c4\n49f939479234b814f18cc3dd172b6d103f0d1aa96008f2c8ced8face0ce829fe\nc88f6e142260772157b19f101e670a43a42cbd606b4c0224464972757c16ed4a\n249e5a3df21a4d137ab8b538f527d6a5ebfe2e03a641f30e6074de30b6078e2c\n08c255a21dc8753a9a430d0c3ee126b04bfb4da575f97d0844443537e3b26efa\n162ef186b9b0e7482efb3e3d1e127f0c4b68a615063f152832c04470e7b45b29\nef7881bc4e4e7387b616e9da6dc62a89a303d0dde8f9bdb5a7364717d09688eb\n5b4a41874b980ef71f1a4e4e5f4dae4cf4fcdf4cb7f8bb852a15fde28d10edfb\n3d838492a3449a5157c6cdc6ae89b5ee4417eccb3cb5cec813a75e0c8c6ea708\n24ed8259cd8da3f63ac89d2c5749af561ae74f52b94b1f396abdee3009384285\n283e87a8effcc0d5b1aa7775de07fa3ceca097514d2589d3f7f5b5094083b151\nb594ccc4a922b8a5ffdb52cd73c3d9cd1e60efde7c528afe937ef6f4e49f2d01\nabfabebf8f2c8bf471eca93b7bb7357b99cf2285422fffac3e2527bca48c50a9\nd077f68a5829d81bc4303e68fc411a116350981d667beb38c1f2de1d33067af2\n"
11:43:33.863895  stderr: level=error msg="Failed to stop all containers: ssh command error:\ncommand : sudo -- sh -c 'crictl stop $(crictl ps -q)'\nerr     : Process exited with status 1\n - E1211 11:43:33.853743   33820 remote_runtime.go:366] \"StopContainer from runtime service failed\" err=\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\" containerID=\"af921fec1672ceb2b9aa3bfb00b2f03bdccca9a3777edeb4ffcffa1dd14dd60e\"\ntime=\"2024-12-11T11:43:33Z\" level=fatal msg=\"stopping the container \\\"af921fec1672ceb2b9aa3bfb00b2f03bdccca9a3777edeb4ffcffa1dd14dd60e\\\": rpc error: code = DeadlineExceeded desc = context deadline exceeded\"\n"
11:43:33.864063  stderr: level=warning msg="Failed to stop all OpenShift containers.\nShutting down VM..."
11:43:33.864145  stderr: level=debug msg="ssh command error:\ncommand : sudo -- sh -c 'crictl stop $(crictl ps -q)'\nerr     : Process exited with status 1\n"
11:43:33.864158  stderr: level=info msg="Stopping the instance, this may take a few minutes..."
11:43:33.864186  stderr: level=debug msg="Stopping \"crc\"..."
11:43:33.864212  stderr: level=debug msg="(crc) Calling .GetState"
11:43:33.864952  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:33Z\" level=debug msg=\"Getting current state...\""
11:43:33.865722  stderr: level=debug msg="(crc) Calling .Stop"
11:43:33.866030  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:33Z\" level=debug msg=\"Stopping VM crc\""
11:43:33.866064  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:33Z\" level=debug msg=\"Getting current state...\""
11:43:34.869236  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:34Z\" level=debug msg=\"Getting current state...\""
11:43:34.870001  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:34Z\" level=debug msg=\"VM state: Running\""
11:43:35.870137  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:35Z\" level=debug msg=\"Getting current state...\""
11:43:35.870870  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:35Z\" level=debug msg=\"VM state: Running\""
11:43:36.871117  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:36Z\" level=debug msg=\"Getting current state...\""
11:43:36.871479  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:36Z\" level=debug msg=\"VM state: Running\""
11:43:37.871834  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:37Z\" level=debug msg=\"Getting current state...\""
11:43:37.872096  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:37Z\" level=debug msg=\"VM state: Running\""
11:43:38.872471  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:38Z\" level=debug msg=\"Getting current state...\""
11:43:38.872790  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:38Z\" level=debug msg=\"VM state: Running\""
11:43:39.873746  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:39Z\" level=debug msg=\"Getting current state...\""
11:43:39.874325  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:39Z\" level=debug msg=\"VM state: Running\""
11:43:40.874619  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:40Z\" level=debug msg=\"Getting current state...\""
11:43:40.874850  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:40Z\" level=debug msg=\"VM state: Running\""
11:43:41.875197  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:41Z\" level=debug msg=\"Getting current state...\""
11:43:41.875517  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:41Z\" level=debug msg=\"VM state: Running\""
11:43:42.876795  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:42Z\" level=debug msg=\"Getting current state...\""
11:43:42.877080  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:42Z\" level=debug msg=\"VM state: Running\""
11:43:43.877469  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:43Z\" level=debug msg=\"Getting current state...\""
11:43:43.877787  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:43Z\" level=debug msg=\"VM state: Running\""
11:43:44.878704  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:44Z\" level=debug msg=\"Getting current state...\""
11:43:44.878959  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:44Z\" level=debug msg=\"VM state: Running\""
11:43:45.879301  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:45Z\" level=debug msg=\"Getting current state...\""
11:43:45.879911  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:45Z\" level=debug msg=\"VM state: Running\""
11:43:46.880080  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:46Z\" level=debug msg=\"Getting current state...\""
11:43:46.880694  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:46Z\" level=debug msg=\"VM state: Running\""
11:43:47.880976  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:47Z\" level=debug msg=\"Getting current state...\""
11:43:47.881590  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:47Z\" level=debug msg=\"VM state: Running\""
11:43:48.881836  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:48Z\" level=debug msg=\"Getting current state...\""
11:43:48.882152  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:48Z\" level=debug msg=\"VM state: Running\""
11:43:49.883180  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:49Z\" level=debug msg=\"Getting current state...\""
11:43:49.883601  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:49Z\" level=debug msg=\"VM state: Running\""
11:43:50.884010  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:50Z\" level=debug msg=\"Getting current state...\""
11:43:50.884361  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:50Z\" level=debug msg=\"VM state: Running\""
11:43:51.884778  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:51Z\" level=debug msg=\"Getting current state...\""
11:43:51.885224  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:51Z\" level=debug msg=\"VM state: Running\""
11:43:52.885600  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:52Z\" level=debug msg=\"Getting current state...\""
11:43:52.885871  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:52Z\" level=debug msg=\"VM state: Running\""
11:43:53.886296  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:53Z\" level=debug msg=\"Getting current state...\""
11:43:53.886586  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:53Z\" level=debug msg=\"VM state: Running\""
11:43:54.887520  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:54Z\" level=debug msg=\"Getting current state...\""
11:43:54.888089  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:54Z\" level=debug msg=\"VM state: Running\""
11:43:55.888308  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:55Z\" level=debug msg=\"Getting current state...\""
11:43:55.888908  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:55Z\" level=debug msg=\"VM state: Running\""
11:43:56.889124  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:56Z\" level=debug msg=\"Getting current state...\""
11:43:56.889594  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:56Z\" level=debug msg=\"VM state: Running\""
11:43:57.890016  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:57Z\" level=debug msg=\"Getting current state...\""
11:43:57.890205  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:57Z\" level=debug msg=\"VM state: Running\""
11:43:58.890592  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:58Z\" level=debug msg=\"Getting current state...\""
11:43:58.890965  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:58Z\" level=debug msg=\"VM state: Running\""
11:43:59.891887  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:59Z\" level=debug msg=\"Getting current state...\""
11:43:59.892138  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:43:59Z\" level=debug msg=\"VM state: Running\""
11:44:00.892561  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:00Z\" level=debug msg=\"Getting current state...\""
11:44:00.892816  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:00Z\" level=debug msg=\"VM state: Running\""
11:44:01.893176  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:01Z\" level=debug msg=\"Getting current state...\""
11:44:01.893840  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:01Z\" level=debug msg=\"VM state: Running\""
11:44:02.894059  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:02Z\" level=debug msg=\"Getting current state...\""
11:44:02.894261  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:02Z\" level=debug msg=\"VM state: Running\""
11:44:03.895278  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:03Z\" level=debug msg=\"Getting current state...\""
11:44:03.895627  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:03Z\" level=debug msg=\"VM state: Running\""
11:44:04.896024  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:04Z\" level=debug msg=\"Getting current state...\""
11:44:04.896602  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:04Z\" level=debug msg=\"VM state: Running\""
11:44:05.896841  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:05Z\" level=debug msg=\"Getting current state...\""
11:44:05.897455  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:05Z\" level=debug msg=\"VM state: Running\""
11:44:06.897645  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:06Z\" level=debug msg=\"Getting current state...\""
11:44:06.897935  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:06Z\" level=debug msg=\"VM state: Running\""
11:44:07.898322  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:07Z\" level=debug msg=\"Getting current state...\""
11:44:07.899972  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:07Z\" level=debug msg=\"VM state: Running\""
11:44:08.899997  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:08Z\" level=debug msg=\"Getting current state...\""
11:44:08.900277  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:08Z\" level=debug msg=\"VM state: Running\""
11:44:09.900619  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:09Z\" level=debug msg=\"Getting current state...\""
11:44:09.901070  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:09Z\" level=debug msg=\"VM state: Running\""
11:44:10.901371  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:10Z\" level=debug msg=\"Getting current state...\""
11:44:10.901649  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:10Z\" level=debug msg=\"VM state: Running\""
11:44:11.902027  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:11Z\" level=debug msg=\"Getting current state...\""
11:44:11.902322  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:11Z\" level=debug msg=\"VM state: Running\""
11:44:12.902725  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:12Z\" level=debug msg=\"Getting current state...\""
11:44:12.902894  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:12Z\" level=debug msg=\"VM state: Running\""
11:44:13.904131  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:13Z\" level=debug msg=\"Getting current state...\""
11:44:13.904372  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:13Z\" level=debug msg=\"VM state: Running\""
11:44:14.904756  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:14Z\" level=debug msg=\"Getting current state...\""
11:44:14.905030  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:14Z\" level=debug msg=\"VM state: Running\""
11:44:15.905463  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:15Z\" level=debug msg=\"Getting current state...\""
11:44:15.905813  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:15Z\" level=debug msg=\"VM state: Running\""
11:44:16.906197  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:16Z\" level=debug msg=\"Getting current state...\""
11:44:16.906772  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:16Z\" level=debug msg=\"VM state: Running\""
11:44:17.906986  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:17Z\" level=debug msg=\"Getting current state...\""
11:44:17.907214  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:17Z\" level=debug msg=\"VM state: Running\""
11:44:18.908397  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:18Z\" level=debug msg=\"Getting current state...\""
11:44:18.908713  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:18Z\" level=debug msg=\"VM state: Running\""
11:44:19.909093  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:19Z\" level=debug msg=\"Getting current state...\""
11:44:19.909358  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:19Z\" level=debug msg=\"VM state: Running\""
11:44:20.909769  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:20Z\" level=debug msg=\"Getting current state...\""
11:44:20.910006  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:20Z\" level=debug msg=\"VM state: Running\""
11:44:21.910393  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:21Z\" level=debug msg=\"Getting current state...\""
11:44:21.910983  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:21Z\" level=debug msg=\"VM state: Running\""
11:44:22.911186  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:22Z\" level=debug msg=\"Getting current state...\""
11:44:22.911451  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:22Z\" level=debug msg=\"VM state: Running\""
11:44:23.912671  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:23Z\" level=debug msg=\"Getting current state...\""
11:44:23.912948  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:23Z\" level=debug msg=\"VM state: Running\""
11:44:24.913323  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:24Z\" level=debug msg=\"Getting current state...\""
11:44:24.913655  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:24Z\" level=debug msg=\"VM state: Running\""
11:44:25.914065  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:25Z\" level=debug msg=\"Getting current state...\""
11:44:25.914539  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:25Z\" level=debug msg=\"VM state: Running\""
11:44:26.914831  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:26Z\" level=debug msg=\"Getting current state...\""
11:44:26.915108  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:26Z\" level=debug msg=\"VM state: Running\""
11:44:27.915455  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:27Z\" level=debug msg=\"Getting current state...\""
11:44:27.915932  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:27Z\" level=debug msg=\"VM state: Running\""
11:44:28.917060  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:28Z\" level=debug msg=\"Getting current state...\""
11:44:28.917316  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:28Z\" level=debug msg=\"VM state: Running\""
11:44:29.917746  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:29Z\" level=debug msg=\"Getting current state...\""
11:44:29.918077  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:29Z\" level=debug msg=\"VM state: Running\""
11:44:30.918503  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:30Z\" level=debug msg=\"Getting current state...\""
11:44:30.918893  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:30Z\" level=debug msg=\"VM state: Running\""
11:44:31.919225  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:31Z\" level=debug msg=\"Getting current state...\""
11:44:31.919578  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:31Z\" level=debug msg=\"VM state: Running\""
11:44:32.919953  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:32Z\" level=debug msg=\"Getting current state...\""
11:44:32.920263  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:32Z\" level=debug msg=\"VM state: Running\""
11:44:33.921613  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:33Z\" level=debug msg=\"Getting current state...\""
11:44:33.922023  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:33Z\" level=debug msg=\"VM state: Running\""
11:44:34.922435  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:34Z\" level=debug msg=\"Getting current state...\""
11:44:36.166622  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:36Z\" level=debug msg=\"VM state: Running\""
11:44:37.166842  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:37Z\" level=debug msg=\"Getting current state...\""
11:44:37.167394  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:37Z\" level=debug msg=\"VM state: Stopped\""
11:44:37.167927  stderr: level=debug msg="retry loop: attempt 0"
11:44:37.167958  stderr: level=debug msg="(crc) Calling .GetState"
11:44:37.168225  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:37Z\" level=debug msg=\"Getting current state...\""
11:44:37.168780  stderr: level=debug msg="Machine \"crc\" was stopped."
11:44:37.168797  stderr: level=debug msg="(crc) Calling .GetState"
11:44:37.168997  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:37Z\" level=debug msg=\"Getting current state...\""
11:44:37.169867  stderr: level=debug msg="Making call to close driver server"
11:44:37.169898  stderr: level=debug msg="(crc) Calling .Close"
11:44:37.170230  stderr: level=debug msg="(crc) DBG | time=\"2024-12-11T11:44:37Z\" level=debug msg=\"Closing plugin on server side\""
11:44:37.170267  stderr: level=debug msg="Successfully made call to close driver server"
11:44:37.170295  stderr: level=debug msg="Making call to close connection to plugin binary"
11:44:37.173386  stdout: Stopped the instance
11:44:37.173468  stderr: level=warning msg="Failed to remove crc contexts from kubeconfig: <nil>"
11:44:37.178890  stdout: exitCodeOfLastCommandInShell=0
11:44:37.179448    bash: oc whoami
11:44:37.304428  stderr: error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
11:44:37.304455  stderr: 
11:44:37.304458  stderr: 
11:44:37.304462  stderr:   1. Via the command-line flag --kubeconfig
11:44:37.304464  stderr:   2. Via the KUBECONFIG environment variable
11:44:37.304467  stderr:   3. In your home directory as ~/.kube/config
11:44:37.304470  stderr: 
11:44:37.304473  stderr: To view or setup config directly use the 'config' command.
11:44:37.311940  stdout: exitCodeOfLastCommandInShell=1
11:44:37.312521    bash: crc status
11:44:37.373730  stderr: level=debug msg="CRC version: 2.45.0+7aeb3b\n"
11:44:37.373762  stderr: level=debug msg="OpenShift version: 4.17.7\n"
11:44:37.373770  stderr: level=debug msg="MicroShift version: 4.17.7\n"
11:44:37.373780  stderr: level=debug msg="Running 'crc status'"
11:44:37.437577  stderr: Error getting ip: host is not running
11:44:37.437607  stderr: 
11:44:37.441882  stdout: exitCodeOfLastCommandInShell=1
```

### Additional context

Might be related with https://github.com/crc-org/crc/issues/1742

### PR DESCRIPTION
**Pull request by anjannath**
## Description

for crc status command to get some VM information like disk-usage, pv count, etc. we need to SSH into the  VM but this is only possible when the VM is running

in case the state of the VM is not Running it will now return early without trying to fetch those  additional information which results in the following error:
```
Error getting ip: host is not running
```

Fixes: #4512 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change
- [ ] Chore (non-breaking change which doesn't affect codebase;
  test, version modification, documentation, etc.)

## Proposed changes

Return early from `client.Status()` when VM state is not `Running`

## Testing

1. `crc status` succeeds after `crc stop` on linux

## Contribution Checklist
- [x] I have read the [contributing guidelines](https://github.com/crc-org/crc/blob/main/developing.adoc)
- [x] My code follows the style guidelines of this project
- [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I tested my code on specified platforms 
    - [x] Linux
    - [ ] Windows
    - [x] MacOS

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

File: pkg/crc/machine/status.go [hunk 1]
```diff
@@ -35,6 +35,10 @@ func (client *client) Status() (*types.ClusterStatusResult, error) {
 		return nil, errors.Wrap(err, "Cannot get machine state")
 	}
 
+	if vmStatus != state.Running {
+		return createClusterStatusResult(vmStatus, vm.bundle.GetBundleType(), vm.bundle.GetVersion(), "", 0, 0, 0, 0, 0, 0, nil)
```
Comment (gbraad) [inline pkg/crc/machine/status.go]: The code is quite cryptic, so an inline comment might be helpful to clearly indicate what happens. description is not enough top determine what the cluster result is.

**Review by gbraad — CHANGES_REQUESTED** [review]

File: pkg/crc/machine/status.go (hunk 1 above)
Comment (albfan) [reply pkg/crc/machine/status.go]: network-mode is not even an option on windows and mac, so probably we can merge https://github.com/crc-org/crc/pull/4514 and set linux as network-mode user too.

Then we can rework this to detect linux, and network-mode to system. That would clarify why quick early with a madeup cluster is needed as network-mode system needs vm running to work

Comment (anjannath) [reply pkg/crc/machine/status.go]: > The code is quite cryptic, so an inline comment might be helpful to clearly indicate what happens. description is not enough top determine what the cluster result is.

added a inline comment in and also updated the commit description, as earlier it was wrong, the IP is actually needed to get the openshift cluster status

Comment (praveenkumar) [reply pkg/crc/machine/status.go]: how about following, this way it doesn't look cryptic and for both network mode it follows same path to get the IP since ram/disksize ..etc doesn't return the error but zero values.

```golang
[...]
	ip := ""
	if vmStatus == state.Running {
		ip, err = vm.IP()
		if err != nil {
			return nil, errors.Wrap(err, "Error getting ip")
		}
	}
[...]
```

Comment (anjannath) [reply pkg/crc/machine/status.go]: Thanks, updated the PR!
