### PR TITLE
fix (crc/machine) : KubeContext left in invalid state after crc stop (#1569)

### LINKED ISSUE #1569: [BUG] After stopping CRC the Kube context is left in inconsistent state causing timeouts
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
CodeReady Containers version: 1.15.0+e317bed
OpenShift version: 4.5.7 (embedded in binary)
  
## CRC status
DEBU CodeReady Containers version: 1.15.0+e317bed 
DEBU OpenShift version: 4.5.7 (embedded in binary) 
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     12.8GB
Cache Directory: /Users/deboer/.crc/cache

## CRC config
no output

## Host Operating System
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021

### Steps to reproduce

  1. crc start
  2. crc stop
  3. kubectl get pods, odo push, or basically anything that uses the kube context

### Expected
If I connect to a remote OpenShift cluster or use other local Kube tools and then disconnect/stop, the Kube context is left pointing to a cluster that I can't connect to anymore, but it 'fails fast': tools that try to connect fail immediately.

e.g. after stopping minikube and running 'kubectl get pods' it immediately responds with:
`The connection to the server localhost:8080 was refused - did you specify the right host or port?`
I expect CRC to have the same behaviour.

### Actual
After stopping CRC the Kube context is left pointing to a cluster (api-crc-testing or api.crc.testing) on a bridge network (192.168.*). For some reason clients can't tell this host doesn't exist anymore and connections to it don't fail fast, which eventually causes timeouts on the client side. This is bad enough with kubectl (20s timeout?), but odo has an even longer timeout (4min?) which makes it unusable and appear to hang.

When stopping CRC please remove the kube context, remove the bridge network, remove the host resolution, or do something similar so that clients can tell it doesn't exist or will fail immediately trying to connect.

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #1569

At the moment, we are only cleaning up crc context from kubeconfig during `crc delete`. This can be problematic if user tries to run any cluster related command after running `crc stop` as kubeconfig still points to CRC cluster that is not active.

I checked minikube's behavior and noticed it's cleaning up kube config in case of both stop and delete commands. Make crc behavior consistent with minikube and perform kubeconfig cleanup in both sub commands.

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://github.com/crc-org/crc/blob/main/developing.adoc)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [x] I tested my code on specified platforms
   - [x] Linux
   - [ ] Windows
   - [ ] MacOS

**Fixes:** Issue #1569

**Relates to:** Issue #1569

## Solution/Idea

Clean up `.kube/config` file while doing `crc stop` in order to not leave kubeconfig in an inconsistent state.

Currently after crc stop `.kube/config` file is left pointing to an outdated kube-context : 
```yaml
  current-context: default/api-crc-testing:6443/kubeadmin
```

This results in timeouts on the client side when user tries to access cluster using any kube client `oc`/`kubectl`:
```
crc : $ time oc get pods
E1015 15:46:38.452130   72163 memcache.go:265] couldn't get current server API group list: Get "https://api.crc.testing:6443/api?timeout=32s": context deadline exceeded - error from a previous attempt: read tcp 127.0.0.1:35058->127.0.0.1:6443: read: connection reset by peer
E1015 15:47:10.615173   72163 memcache.go:265] couldn't get current server API group list: client rate limiter Wait returned an error: context deadline exceeded - error from a previous attempt: read tcp 127.0.0.1:38388->127.0.0.1:6443: read: connection reset by peer
E1015 15:47:43.548507   72163 memcache.go:265] couldn't get current server API group list: client rate limiter Wait returned an error: context deadline exceeded - error from a previous attempt: read tcp 127.0.0.1:55098->127.0.0.1:6443: read: connection reset by peer
E1015 15:48:15.549643   72163 memcache.go:265] couldn't get current server API group list: Get "https://api.crc.testing:6443/api?timeout=32s": context deadline exceeded - error from a previous attempt: read tcp 127.0.0.1:35854->127.0.0.1:6443: read: connection reset by peer
E1015 15:48:47.550725   72163 memcache.go:265] couldn't get current server API group list: Get "https://api.crc.testing:6443/api?timeout=32s": context deadline exceeded - error from a previous attempt: read tcp 127.0.0.1:44620->127.0.0.1:6443: read: connection reset by peer
error: Get "https://api.crc.testing:6443/api?timeout=32s": context deadline exceeded - error from a previous attempt: read tcp 127.0.0.1:44620->127.0.0.1:6443: read: connection reset by peer

real    2m41.162s
user    0m0.150s
sys     0m0.059s

```
This pull request would clean up `.kube/config` to align crc behavior with minikube so that it fails fast now:
Trying to access cluster after crc stop
```
crc : $ time oc get pods
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:


  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

real    0m0.126s
user    0m0.062s
sys     0m0.051s
```

## Proposed changes

Add a call to `cleanKubeconfig` in `stop.go` to clean up kubeconfig while stopping cluster. 

## Testing

In order to test this branch you need to follow these steps:
1. `make cross` to build `crc` binary
2. Set up a new cluster with created crc binary
    - `./out/linux-amd64/crc setup`
    - `./out/linux-amd64/crc start`
    - `./out/linux-amd64/crc stop`
3. Verify whether `.kube/config` is cleaned up after `crc stop`
```bash
crc : $ ./out/linux-amdcat ~/.kube/config 
apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null
```
5. Verify whether when accessing stopped cluster with `kubectl` / `oc` it fails fast:
```
crc : $ ./out/linux-amd./out/linux-amd64/crc stop
INFO Stopping the instance, this may take a few minutes... 
Stopped the instance
crc : $ kubectl get opds
E1015 14:29:44.984352   64932 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E1015 14:29:44.984593   64932 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E1015 14:29:44.985937   64932 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E1015 14:29:44.986265   64932 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E1015 14:29:44.987715   64932 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?

```

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Could anyone please help me understand [CI failures in the Windows-QE pipeline](https://github.com/crc-org/crc/actions/runs/11348082021/job/31561020502)? Could it be a flaky failure? From the GitHub action logs, it seems that an action failed to generate a report. I'm not entirely sure whether these failures are related to changes made in this pull request.

**Comment by redbeam** [comment]
@rohanKanojia I would say they are related to something else, since these two pipelines fail for me too in #4343 .

**Comment by gbraad** [comment]
@adrianriobo and @lilyLuLiu can help you with this

**Comment by lilyLuLiu** [comment]
[CI failures in the Windows-QE pipeline](https://github.com/crc-org/crc/actions/runs/11348082021/job/31561020502) failed in [copy test resource to target machine](https://github.com/crc-org/crc/actions/runs/11348082021/job/31561020502#:~:text=%2B-,scp%20%2Dr%20%2Do%20StrictHostKeyChecking%3Dno%20%2Do%20UserKnownHostsFile%3D/dev/null%20%2Do%20ServerAliveInterval,scp%3A%20Connection%20closed,-349), this is qe related, not because of this pr. 
@adrianriobo we need to improve the failure handing for the deliverset.

**Comment by rohanKanojia** [comment]
@lilyLuLiu : Is there any open issue to track this?

**Comment by lilyLuLiu** [comment]
@rohanKanojia https://github.com/adrianriobo/deliverest/issues/50

File: pkg/crc/machine/stop.go [hunk 1]
```diff
@@ -9,6 +11,11 @@ import (
 )
 
 func (client *client) Stop() (state.State, error) {
+	if err := cleanKubeconfig(getGlobalKubeConfigPath(), getGlobalKubeConfigPath()); err != nil {
+		if !errors.Is(err, os.ErrNotExist) {
+			logging.Warnf("Failed to remove crc contexts from kubeconfig: %v", err)
+		}
+	}
```
Comment (praveenkumar) [inline pkg/crc/machine/stop.go]: @rohanKanojia this block of code should be at the end, we shouldn't clean the kubeconfig until stop the instance first.

Comment (rohanKanojia) [reply pkg/crc/machine/stop.go]: I had moved this above in order to make it easier to test. I had added tests in kubeconfig_test to verify that calling cleanupKubeconfig multiple times wouldn't affect kubeconfig.

Let me try to adapt tests after moving it to the bottom.

Comment (rohanKanojia) [reply pkg/crc/machine/stop.go]: Hello, on second thought from the user's perspective, we should always clean up `.kube/config` regardless of whether the instance was stopped successfully or not (to avoid an inconsistent state, which was the problem user was facing).

Do you think it would be okay if we move this cleanup statement in a `defer` block ?
```go
	defer func(input, output string) {
		err := cleanKubeconfig(input, output)
		if !errors.Is(err, os.ErrNotExist) {
			logging.Warnf("Failed to remove crc contexts from kubeconfig: %v", err)
		}
	}(getGlobalKubeConfigPath(), getGlobalKubeConfigPath())
```

Comment (praveenkumar) [reply pkg/crc/machine/stop.go]: yes, having it part of defer would be also good so that it is execute regardless.

File: test/e2e/testsuite/testsuite.go [hunk 2]
```diff
@@ -1025,6 +1028,29 @@ func EnsureUserNetworkmode() error {
...
 }
 
+func EnsureKubeConfigIsCleanedUp() error {
+	kubeConfig, cfg, err := machine.GetGlobalKubeConfig()
+	if err != nil {
+		return err
+	}
+	if len(kubeConfig) == 0 {
+		fmt.Println("Unable to load kubeconfig file")
+		os.Exit(1)
```
Comment (praveenkumar) [inline test/e2e/testsuite/testsuite.go]: should we return error here or exit? I think if we exit then other test is not run which we don't want.
