### PR TITLE
fix (daemon) : Add `docker.internal` entry to virtual network DNS config (#3784)

### LINKED ISSUE #3784: [BUG] Add `.docker.internal` entries to `cmd/crc/cmd/daemon.go` ?
This would match what is being done in https://github.com/containers/gvisor-tap-vsock/pull/251

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fixes: #3784

Port of https://github.com/containers/gvisor-tap-vsock/pull/251 to add `docker.internal.` DNS record to CRC daemon virtual network config.

Relates to: PR https://github.com/containers/gvisor-tap-vsock/pull/251

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change
- [ ] Chore (non-breaking change which doesn't affect codebase;
  test, version modification, documentation, etc.)

## Proposed changes

+ Move virtualNetwork config construction to a method so that it becomes testable
+ Add another entry to DNS zones for `docker.internal.`

## Testing

I've only verified it using a unit test.

## Contribution Checklist
- [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Which platform have you tested the code changes on? 
    - [x] Linux
    - [ ] Windows
    - [ ] MacOS

### CODE REVIEW

File: cmd/crc/cmd/daemon.go [hunk 1]
```diff
@@ -66,69 +66,83 @@ var daemonCmd = &cobra.Command{
...
+		if virtualNetworkConfig.NAT == nil {
+			virtualNetworkConfig.NAT = make(map[string]string)
 		}
-		virtualNetworkConfig.GatewayVirtualIPs = []string{hostVirtualIP}
-		err := run(&virtualNetworkConfig)
-		return err
-	},
+		virtualNetworkConfig.NAT[hostVirtualIP] = "127.0.0.1"
+	}
+	virtualNetworkConfig.GatewayVirtualIPs = []string{hostVirtualIP}
```
Comment (evidolob) [inline cmd/crc/cmd/daemon.go]: Minor comment, I think `GatewayVirtualIPs` initialisation could be moved in to struct initialisation, it will slightly improve this code.

**Review by evidolob — APPROVED** [review]

File: cmd/crc/cmd/daemon.go (hunk 1 above)
Comment (rohanKanojia) [reply cmd/crc/cmd/daemon.go]: Thanks for your suggestion! I've moved it to struct initialization block.
