### PR TITLE
Validate proxy taken from env variables and allow only absolute paths for config proxy-ca-file

### LINKED ISSUE #3690: [BUG] Invalid `proxy-ca-file` path prevents crc from starting
### General information

  * OS: Linux
  * Hypervisor: KVM

## CRC version
```bash
# Put `crc version` output here
$ ./out/linux-amd64/crc version
FATA[0000] not able to read proxy CA data from /home/teuf/crc/crc/images/squid/pki/rootCA.crt: open /home/teuf/crc/crc/images/squid/pki/rootCA.crt: no such file or directory 
```
(yes it is that bad)
  
## CRC config
```bash
# Put `crc config view` output here
$ ./out/linux-amd64/crc view
FATA[0000] not able to read proxy CA data from /home/teuf/crc/crc/images/squid/pki/rootCA.crt: open /home/teuf/crc/crc/images/squid/pki/rootCA.crt: no such file or directory 
```

### Steps to reproduce

  1. set `proxy-ca-file` to a valid path
  2. remove the file

### Expected

`crc` errors out when it tries to configure a VM with a proxy

### Actual

All `crc` invocations (`config`, `version`, ...) print a proxy-ca-file related error message and exit.
The config file must be edited by hand to get out of this.

This could be worked on at the same time as https://github.com/crc-org/crc/issues/3641

### PR DESCRIPTION
**Pull request by anjannath**
- validate proxy urls taken from env vairbles
- validate that proxy certificate file exists before trying to read it
- only allow absolute paths for the `proxy-ca-file` config setting

Fixes #3690 #3098 #3641

### CODE REVIEW

**Comment by cfergeau** [comment]
Can `config: make proxy-ca-file only accept absolute paths` cause existing configs to stop working?
Would it be possible to convert relative to absolute and to use absolute throughout crc's codebase? This would be more user-friendly.

**Comment by anjannath** [comment]
> Can `config: make proxy-ca-file only accept absolute paths` cause existing configs to stop working? 

no, existing configs should keep working, the stricter validation only happens when user configures a value via `crc config set`, when retrieving the value for use by other parts in the codebase the validation will not run

> Would it be possible to convert relative to absolute and to use absolute throughout crc's codebase? This would be more user-friendly.

yeah it'll better, but this would mean we need to mutate the config value after user has provided it, currently in the config pkg we don't have such provisions, i was thinking to follow the same pattern as the _change notifiers_ (and call it _mutators_) did you have another idea on how to implement this?

**Comment by cfergeau** [comment]
> > Would it be possible to convert relative to absolute and to use absolute throughout crc's codebase? This would be more user-friendly.
> 
> yeah it'll better, but this would mean we need to mutate the config value after user has provided it, currently in the config pkg we don't have such provisions, i was thinking to follow the same pattern as the _change notifiers_ (and call it _mutators_) did you have another idea on how to implement this?

I had https://github.com/cfergeau/crc/commit/2d5e48887ba1a537bd8ab949e9283f31e8898beb in the back of my mind, which seems to work as expected after some quick prototyping (only test I did is what is in the unit test)

**Comment by anjannath** [comment]
> I had [cfergeau@2d5e488](https://github.com/cfergeau/crc/commit/2d5e48887ba1a537bd8ab949e9283f31e8898beb) in the back of my mind, which seems to work as expected after some quick prototyping (only test I did is what is in the unit test)

i was thinking to implement it like this: https://github.com/anjannath/crc/commit/5d87b1dff4328194939d2901490f46f702b536b8 but with the `Path` type i think its better, as while adding the config setting its clear, will take your commit do some more testing and update the PR, thanks!

File: pkg/crc/network/httpproxy/proxy.go [hunk 1]
```diff
@@ -66,10 +68,14 @@ func NewProxyDefaults(httpProxy, httpsProxy, noProxy, proxyCAFile string) (*Prox
 	envProxy := httpproxy.FromEnvironment()
 
 	if DefaultProxy.HTTPProxy == "" {
-		DefaultProxy.HTTPProxy = envProxy.HTTPProxy
+		if err := ValidateProxyURL(envProxy.HTTPProxy, false); err == nil {
+			DefaultProxy.HTTPProxy = envProxy.HTTPProxy
```
Comment (cfergeau) [inline pkg/crc/network/httpproxy/proxy.go]: When there is an error, I'd add a warning so that it's clear proxy from the environment is being ignored.

File: pkg/crc/network/httpproxy/proxy.go [hunk 2]
```diff
@@ -45,6 +46,9 @@ func readProxyCAData(proxyCAFile string) (string, error) {
 	if proxyCAFile == "" || !filepath.IsAbs(proxyCAFile) {
 		return "", nil
 	}
+	if !crcos.FileExists(proxyCAFile) {
+		return "", nil
```
Comment (cfergeau) [inline pkg/crc/network/httpproxy/proxy.go]: Is there a validation happening later on? Ideally, most crc commands would not fail when the proxy config is invalid. It's probably only `crc config`, `crc setup` and `crc start` which should report a hard failure when the proxy is invalid, the other ones are not dependent on the proxy settings.

Comment (anjannath) [reply pkg/crc/network/httpproxy/proxy.go]: > Is there a validation happening later on? 

no, there's validation when running `config set`. and then here when proxy is being setup which is very early on in `root.go`.  (we send telemetry data from each command, and that uses the proxy settings)

> It's probably only crc config, crc setup and crc start which should report a hard failure when the proxy is invalid, the other ones are not dependent on the proxy settings.

maybe for these commands we can re-validate (add a "re-validation" helper in proxy package) the proxy settings and this will be hard failure if validation fails

File: pkg/crc/network/httpproxy/proxy.go (hunk 1 above)
Comment (anjannath) [reply pkg/crc/network/httpproxy/proxy.go]: added a warning msg

File: pkg/crc/network/httpproxy/proxy.go (hunk 2 above)
Comment (anjannath) [reply pkg/crc/network/httpproxy/proxy.go]: Thinking about this again, doing this selective hard failure for `start` and `setup` seems not to be necessary, as we have added validation of proxy config from environment, now it should not be possible to configure invalid proxy settings at all via the environment or via `crc config set`

for the `proxy-ca-file` we have validation while `config set` is used to make sure the file exists, and with the conversion of relative to absolute paths, user shouldn't end up in a situation where they have invalid path to `proxy-ca-file`

now the only way invalid proxy settings can end up in the config is by manually editing the config file, which i think should be a hard failure for all the commands, WDYT?

Comment (cfergeau) [reply pkg/crc/network/httpproxy/proxy.go]: > for the proxy-ca-file we have validation while config set is used to make sure the file exists, and with the conversion of relative to absolute paths, user shouldn't end up in a situation where they have invalid path to proxy-ca-file

it's a user problem, but
```
$ crc config set proxy-ca-file foo.crt
$ rm foo.crt
```

> Thinking about this again, doing this selective hard failure for start and setup seems not to be necessary, as we have added validation of proxy config from environment, now it should not be possible to configure invalid proxy settings at all via the environment or via crc config set

We validate the proxy config, and if for example `HTTP_PROXY` is invalid in the environment, we ignore it right?
If the user made a typo when setting it, it's better to make this very visible than ignoring it, no?

Comment (cfergeau) [reply pkg/crc/network/httpproxy/proxy.go]: If there are already warnings for all of this every time crc starts up, it might be enough ,I'll have to check how it looks :)

Comment (anjannath) [reply pkg/crc/network/httpproxy/proxy.go]: > We validate the proxy config, and if for example HTTP_PROXY is invalid in the environment, we ignore it right?
If the user made a typo when setting it, it's better to make this very visible than ignoring it, no?

yes i changed that its not silently ignoring it now. If the configured `proxy-ca-file` path is not present, it returns an error which is a hard failure for the all the commands, also with a msg asking user to either unset or correct the config

File: pkg/crc/network/httpproxy/proxy.go [hunk 3]
```diff
@@ -41,7 +42,7 @@ func (p *ProxyConfig) String() string {
 }
 
 func readProxyCAData(proxyCAFile string) (string, error) {
-	if proxyCAFile == "" {
+	if proxyCAFile == "" || !filepath.IsAbs(proxyCAFile) {
```
Comment (cfergeau) [inline pkg/crc/network/httpproxy/proxy.go]: I'm not sure why we want to ignore the error in this situation?

File: pkg/crc/network/httpproxy/proxy.go [hunk 4]
```diff
@@ -75,11 +75,15 @@ func NewProxyDefaults(httpProxy, httpsProxy, noProxy, proxyCAFile string) (*Prox
...
 			DefaultProxy.HTTPProxy = envProxy.HTTPProxy
+		} else {
+			logging.Warnf("HTTP_PROXY environment variable is being ignored as it failed validation: %v", err)
 		}
 	}
 	if DefaultProxy.HTTPSProxy == "" {
 		if err := ValidateProxyURL(envProxy.HTTPSProxy, true); err == nil {
 			DefaultProxy.HTTPSProxy = envProxy.HTTPSProxy
+		} else {
+			logging.Warnf("HTTPS_PROXY environment variable is being ignored as it failed validation: %v", err)
```
Comment (cfergeau) [inline pkg/crc/network/httpproxy/proxy.go]: Can these 2 warnings be moved to the first commit?

File: pkg/crc/network/httpproxy/proxy.go [hunk 5]
```diff
@@ -260,3 +264,16 @@ func HTTPTransport() http.RoundTripper {
...
 	return proxyConfig.HTTPTransport()
 }
+
+func RevalidateProxyCAFile() error {
+	proxyConfig, err := NewProxyConfig()
+	if err != nil {
+		return err
+	}
+	if proxyConfig.ProxyCAFile != "" {
+		if proxyConfig.ProxyCACert == "" {
```
Comment (cfergeau) [inline pkg/crc/network/httpproxy/proxy.go]: The 2 commits before this one ignore various errors happening in `readProxyCAData`, this check for `ProxyCACert` is an indirect way of checking if we ignored any errors.
We also ignore invalid proxy settings from the environment, but this will not be detected here (not necessarily mandatory, but would be nice if everything could be reported to the user).

The commit logs are short on details about the bugs that are being fixed, so I'd need to debug this again to see if there are easy alternatives I can suggest to improve this :(

**Review by cfergeau — COMMENTED** [review]
This PR ignores the errors which block startup, and then the code tries to figure out if an error was ignored to report it at the right time. Ideally we could do something more direct, but I'll need to look closer at it.

**Comment by cfergeau** [comment]
These are these lines which are causing an error to happen very early in crc startup:
https://github.com/crc-org/crc/blob/85cc7183e4daf12b148b594a444e1d50546910e3/cmd/crc/cmd/root.go#L58-L60

Would be useful to mention it in one of the commit logs :)


In my opinion, if we want to ignore errors/output a warning, root.go is the place where we should do it, it's the only place calling NewProxyDefaults().

I think you can also add some kind of 'error' field to ProxyConfig, to record that there was an error reading the CA file, and/or that there was an error parsing the proxy from the env, ... Then it becomes easy to check at a later time if there are proxy config errors.
`start` has a call to `getProxyConfig()` relatively early during startup so an explicit "revalidateConfig" may not be needed there.

**Comment by anjannath** [comment]
@cfergeau I've updated the PR with more descriptive commit msg and changed the ignoring of error to happen in root.go, also added a commit to let users know when invalid config is preset in the env variables, PTALA :)

File: pkg/crc/config/validations.go [hunk 6]
```diff
@@ -103,6 +104,17 @@ func validatePath(value interface{}) (bool, string) {
 	return true, ""
 }
 
+func validatePathAbs(value interface{}) (bool, string) {
```
Comment (cfergeau) [inline pkg/crc/config/validations.go]: This could be named `validateAbsolutePath`?

**Review by cfergeau — COMMENTED** [review]
What happens if the user's config has a relative path to a CA file, and they upgrade to a version of crc with validateAbsolutePath? A warning will be printed? Will they still be able to use their relative path CA if it worked for them before?

**Comment by anjannath** [comment]
> What happens if the user's config has a relative path to a CA file, and they upgrade to a version of crc with validateAbsolutePath? A warning will be printed? Will they still be able to use their relative path CA if it worked for them before?

yes, it'll keep working, since the validation only happens when user runs `crc config set proxy-ca-file` but there will be no warning also to ask them to migrate to absolute path..

**Comment by anjannath** [comment]
I forgot about fc4dbfb4e504aaf439557f2cbadb16efd4e902c2 which is more user friendly than the `validaeAbsolutePath`

**Comment by anjannath** [comment]
@cfergeau updated :)

File: pkg/crc/config/config.go [hunk 7]
```diff
@@ -239,11 +239,20 @@ func (c *Config) Get(key string) SettingValue {
 	}
 	return SettingValue{
 		Value:     value,
-		IsDefault: reflect.DeepEqual(setting.defaultValue, value),
```
Comment (cfergeau) [inline pkg/crc/config/config.go]: Good catch!
There's a 
```
case Path, string:
		value = cast.ToString(value)
```
in this function, did you try changing it to:
```
case Path: value = Path(cast.ToString(value))
```
?

Comment (anjannath) [reply pkg/crc/config/config.go]: Yes tried this now, and it also works, updated to use this instead..

File: pkg/crc/config/config.go [hunk 8]
```diff
@@ -200,6 +211,7 @@ func (c *Config) Get(key string) SettingValue {
 		}
 	case string:
 		value = cast.ToString(value)
+	case Path:
```
Comment (cfergeau) [inline pkg/crc/config/config.go:212]: Imo this should be `value = Path(cast.ToString(value))`

File: pkg/crc/config/settings_test.go [hunk 9]
```diff
@@ -158,3 +159,19 @@ func TestUnsetPreset(t *testing.T) {
 		IsSecret:  false,
 	}, cfg.Get(CPUs))
 }
+
+func TestPath(t *testing.T) {
+	cfg, err := newInMemoryConfig()
+	require.NoError(t, err)
```
Comment (cfergeau) [inline pkg/crc/config/settings_test.go:165]: A test for the default value would be useful imo as this was initially buggy.
Something like this should do the trick:

```
	assert.Equal(t, SettingValue{
		Value:     Path(""),
		Invalid:   false,
		IsDefault: true,
		IsSecret:  false,
	}, cfg.Get(ProxyCAFile))
```

File: pkg/crc/config/config.go (hunk 8 above)
Comment (anjannath) [reply pkg/crc/config/config.go:212]: Doing this fails the existing test case, had to wrap the expected value in `Path` and `config view` was not showing the `proxy-ca-file` value for that to work had to also add a stringer method for the `Path` type

**Review by cfergeau — APPROVED** [review]
