### PR TITLE
fix (machine) : crc daemon `/status` api should return correct preset value for `okd` cluster (#4478)

### LINKED ISSUE #4478: [BUG] crc daemon `/status` api returns wrong preset value for `okd` cluster
## Description

Related to #3626

I noticed this issue when I was testing my fix for #3626, I was expecting CRC status will receive preset value as `preset.OKD` but this was not happening. 

Code relies on crc daemon to return cluster status. Upon requesting the API endpoint, I got this response:

Result of running `curl --unix-socket ~/.crc/crc-http.sock http://crc/api/status`
```json
{
  "CrcStatus": "Running",
  "OpenshiftStatus": "Unreachable",
  "OpenshiftVersion": "4.14.0-0.okd-scos-2024-01-10-151818",
  "DiskUse": 16885141504,
  "DiskSize": 32680947712,
  "RAMUse": 1958576128,
  "RAMSize": 9371365376,
  "Preset": "openshift" // Not OK, should be okd
}
```
Upon looking at the code, it looks like we get cluster information via `/status` endpoint where only microshift and openshift presets are handled. We get this response for `/status/` even on an OKD cluster:
https://github.com/crc-org/crc/blob/f71d9cea2c99444488f1358f0217f1ff9be4f2a4/pkg/crc/machine/status.go#L39-L48

## General information

  * OS: Linux 
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop 

## CRC version
```bash
CRC version: 2.32.0+54a6f9
OpenShift version: 4.14.8
Podman version: 4.4.4
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
- consent-telemetry                     : yes
- preset                                : okd
```

## Host Operating System
```bash
NAME="Fedora Linux"
VERSION="41 (KDE Plasma)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=41
VERSION_CODENAME=""
PLATFORM_ID="platform:f41"
PRETTY_NAME="Fedora Linux 41 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:41"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f41/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=41
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=41
SUPPORT_END=2025-12-15
VARIANT="KDE Plasma"
VARIANT_ID=kde
```

### Steps to reproduce

  1. `crc config set preset okd`
  2. `crc setup`
  3. `crc start`
  4. `curl --unix-socket ~/.crc/crc-http.sock http://crc/api/status | jq '.Preset'`  (should return `okd` not `openshift`)

### Expected

 `curl --unix-socket ~/.crc/crc-http.sock http://crc/api/status | jq '.Preset'` should return `okd`

### Actual
 `curl --unix-socket ~/.crc/crc-http.sock http://crc/api/status | jq '.Preset'` returns `openshift`

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #4478

**Relates to:** Issue #4478  #4479

## Solution/Idea

CRC daemon's `/api/status` API endpoint should return correct value of preset when running CRC cluster configured with `crc` preset. At the moment it only returns correct value for `microshift` and `openshift` presets.

## Proposed changes

+ Refactor `Status()` method to move ClusterStatusResult object creation logic to a separate method for easier testing
+ Add case for OKD preset while setting preset value in cluster preset

## Testing
Build a development version of CRC and create a cluster configured with okd preset. Then query status endpoint to see what preset is returned by API server.

1. `crc config set preset okd`
2. `crc setup`
3. `crc start`
4. `curl -i --unix-socket ~/.crc/crc-http.sock http://crc/api/status | jq .Preset` should return `"okd"`

### Old Behavior
Old Response of `/api/status` on OKD based cluster:
```json
{
  "CrcStatus": "Running",
  "OpenshiftStatus": "Unreachable",
  "OpenshiftVersion": "4.14.0-0.okd-scos-2024-01-10-151818",
  "DiskUse": 16885141504,
  "DiskSize": 32680947712,
  "RAMUse": 1958576128,
  "RAMSize": 9371365376,
  "Preset": "openshift" // Not OK, should be okd
}
```

### New Behavior (with this PR)
New Response of `/api/status` on OKD based cluster:
```json
{
  "CrcStatus": "Running",
  "OpenshiftStatus": "Unreachable",
  "OpenshiftVersion": "4.15.0-0.okd-2024-02-23-163410",
  "DiskUse": 521195520,
  "DiskSize": 10947768320,
  "RAMUse": 21496344576,
  "RAMSize": 32680947712,
  "Preset": "okd"
}
```

I have tested by cherry-picking this commit on top of #4479 , it's now displaying OKD value in `crc status` as expected.

### CODE REVIEW

File: pkg/crc/machine/status.go [hunk 1]
```diff
@@ -33,45 +33,53 @@ func (client *client) Status() (*types.ClusterStatusResult, error) {
...
+	if vm.bundle.IsMicroshift() {
+		openShiftStatusSupplier = getMicroShiftStatus
+	}
+
+	return createClusterStatusResult(vmStatus, vm.bundle.GetBundleType(), vm.bundle.GetVersion(), ip, ramSize, ramUse, diskSize, diskUse, pvSize, pvUse, openShiftStatusSupplier)
+}
+
+func createClusterStatusResult(vmStatus state.State, bundleType preset.Preset, vmBundleVersion string, vmIP string,
+	diskSize int64, diskUse int64, ramSize int64, ramUse int64, pvUse int, pvSize int,
+	openShiftStatusSupplier func(context.Context, string) types.OpenshiftStatus) (*types.ClusterStatusResult, error) {
```
Comment (anjannath) [inline pkg/crc/machine/status.go]: nit: maybe you can reduce the length of this line a bit by doing the following, and create a type for the _openShiftStatusSupplier_ func:

```go
type openShiftStatusSupplierFunc func(context.Context, string) types.OpenshiftStatus
```

```suggestion
func createClusterStatusResult(vmStatus state.State, bundleType preset.Preset, vmBundleVersion, vmIP string, diskSize, diskUse, ramSize, ramUse int64, pvUse, pvSize int, openShiftStatusSupplierFunc) (*types.ClusterStatusResult, error) {
```

**Review by anjannath — APPROVED** [review]

**Review by anjannath — APPROVED** [review]
