### PR TITLE
Return ErrNotImplemented from unixgramListener on windows and linux

### LINKED ISSUE #4764: [bug] crc setup fail on windows as `crc daemon` hits panic to invalid pointer reference
crc version: 05.20 main branch
bundle version: 4.18.2
platform: windows

```
PS C:\Users\crcqe> crc setup
CRC is constantly improving and we would like to know more about usage (more details at https://developers.redhat.com/article/tool-data-collection)
Your preference can be changed manually if desired using 'crc config set consent-telemetry <yes/no>'
Would you like to contribute anonymous usage statistics? [y/N]: y
Thanks for helping us! You can disable telemetry with the command 'crc config set consent-telemetry no'.
INFO Using bundle path C:\Users\crcqe\.crc\cache\crc_hyperv_4.18.2_amd64.crcbundle
INFO Checking minimum RAM requirements
INFO Check if Podman binary exists in: C:\Users\crcqe\.crc\bin\oc
INFO Checking if running in a shell with administrator rights
INFO Checking Windows release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if Hyper-V service is enabled
INFO Checking if crc-users group exists
INFO Checking if current user is in crc-users and Hyper-V admins group
INFO Checking if vsock is correctly configured
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if C:\Users\crcqe\.crc\cache\crc_hyperv_4.18.2_amd64.crcbundle exists
INFO Checking if the win32 background launcher is installed
INFO Checking if the daemon task is installed
INFO Installing the daemon task
INFO Checking if the daemon task is running
INFO Running the daemon task
Temporary error: daemon is not running yet (x8)
```

---

running `crc daemon --log-level debug` on windows is failing with following error:

```
PS C:\Users\rhqp> crc daemon --log-level debug
DEBU CRC version: 2.50.0+8caa80
DEBU OpenShift version: 4.18.2
DEBU MicroShift version: 4.18.2
DEBU Running 'crc daemon'
INFO listening \\.\pipe\crc-http
INFO listening vsock://00000400-FACB-11E6-BD58-64006A7986D3
0B sent to the VM, 0B received from the VM
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff6934791d6]

goroutine 92 [running]:
github.com/crc-org/crc/v2/cmd/crc/cmd.run.func4()
        D:/a/crc/crc/cmd/crc/cmd/daemon.go:221 +0x56
created by github.com/crc-org/crc/v2/cmd/crc/cmd.run in goroutine 1
        D:/a/crc/crc/cmd/crc/cmd/daemon.go:212 +0x345

```

### PR DESCRIPTION
**Pull request by vyasgun**
## Description
Error should not be nil in the case of `unixgramListener` implementation in `daemon_linux.go` and `daemon_windows.go`

Relates to: #4764, PR https://github.com/crc-org/crc/pull/4753

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change
- [ ] Chore (non-breaking change which doesn't affect codebase;
  test, version modification, documentation, etc.)

## Contribution Checklist
- [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [x] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Which platform have you tested the code changes on? 
    - [x] Linux
    - [x] Windows
    - [x] MacOS

## Summary by Sourcery

Return ErrNotImplemented for unsupported unixgramListener implementations on Linux and Windows and adjust macOS logging formatting

Bug Fixes:
- Make unixgramListener on Linux return drivers.ErrNotImplemented instead of nil
- Make unixgramListener on Windows return drivers.ErrNotImplemented instead of nil

Enhancements:
- Remove extraneous colon in the logging message for the darwin unixgramListener

### CODE REVIEW

**Comment by anjannath** [comment]
tested on windows 11 and `crc setup` is working now with the changes from this PR

File: cmd/crc/cmd/daemon.go [hunk 1]
```diff
@@ -217,6 +218,10 @@ func run(configuration *types.Configuration) error {
 			if err != nil && !errors.Is(err, net.ErrClosed) {
 				logging.Errorf("unixgramListener error: %v", err)
 			}
+			if errors.Is(err, drivers.ErrNotImplemented) {
```
Comment (cfergeau) [inline cmd/crc/cmd/daemon.go]: Do we want the `logging.Errorf("unixgramListener error: %v", err)` message to trigger in this situation?

File: cmd/crc/cmd/daemon.go [hunk 2]
```diff
@@ -217,6 +218,10 @@ func run(configuration *types.Configuration) error {
...
+				cancel()
```
Comment (cfergeau) [inline cmd/crc/cmd/daemon.go:218]: `unixgramListener` did nothing, so calling `cancel` is likely to be a noop

Comment (vyasgun) [reply cmd/crc/cmd/daemon.go:218]: it is a noop. Not adding it was resulting in `govet` errors.

**Review by cfergeau — APPROVED** [review]
/lgtm
/approve
