### PR TITLE
fix : remove unnecessary logging for `crc-exists` file (#3676)

### LINKED ISSUE #3676: [BUG] Unnecessary logging `crc-exists` every second on Windows grows `crcd.log`
### General information

  * OS: ~Linux~ / ~macOS~ / Windows
  * Hypervisor: ~KVM~ / Hyper-V / ~hyperkit~ / ~vfkit~
  * Did you run `crc setup` before starting it (Yes/~No~)?
  * Running CRC on: Laptop / ~Baremetal-Server~ / ~VM~

The `crcd.log` file grows huge due to the following being logged:
```
time="2023-05-21T12:43:43+08:00" level=debug msg="Running 'Hyper-V\\Get-VM crc | Select-Object -ExpandProperty State'"
time="2023-05-21T12:43:44+08:00" level=debug msg="Checking file: C:\\Users\\gbraad\\.crc\\machines\\crc\\.crc-exist"
time="2023-05-21T12:43:44+08:00" level=debug msg="Checking file: C:\\Users\\gbraad\\.crc\\machines\\crc\\.crc-exist"
```

which is 352 bytes every second, or 1.2672 megabytes every hour, or 30.4128 megabytes every day... just logging this.

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fixes: #3676.

Remove unnecessary debug log statement for `crc-exists` file from filestore Exists() method

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change
- [ ] Chore (non-breaking change which doesn't affect codebase;
  test, version modification, documentation, etc.)

## Proposed changes

Remove unnecessary debug log statement for `crc-exists` file from filestore Exists() method

## Testing

1. Start CRC cluster and monitor crc.log file 
2. It should not have redundant log statement for checking `crc-exists` file

## Contribution Checklist
- [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Which platform have you tested the code changes on? 
    - [x] Linux
    - [x] Windows
    - [ ] MacOS

### CODE REVIEW

File: pkg/libmachine/persist/filestore.go [hunk 1]
```diff
@@ -83,7 +83,6 @@ func (s Filestore) SetExists(name string) error {
 func (s Filestore) Exists(name string) (bool, error) {
 	filename := filepath.Join(s.MachinesDir, name, fmt.Sprintf(".%s-exist", name))
 	_, err := os.Stat(filename)
-	log.Debugf("Checking file: %s", filename)
```
Comment (praveenkumar) [inline pkg/libmachine/persist/filestore.go:86]: This is useful for debugging so I would suggest instead of complete remove better to move it to `os.IsNotExist` block and change message around `file not found: filename`.

Comment (rohanKanojia) [reply pkg/libmachine/persist/filestore.go:86]: thanks, I've moved the debug statement to `os.IsNotExist` block

**Comment by gbraad** [comment]
/me high-fives @rohanKanojia; "Yes! Finally ..." ✋
