### PR TITLE
[QE] Set env var windows

### LINKED ISSUE #4618: [QE] integration: Setting env var on windows fail
### General information

crc might be setting boolean parameters incorrectly

### Operating System

Windows

### Hypervisor

Hyper-V

### Did you run `crc setup` before `crc start`?

yes

### Running on

Laptop

### Steps to reproduce

test disable update check

### CRC version

```shell

```

### CRC status

```shell

```

### CRC config

```shell

```

### Host Operating System

```shell
windows 10
```

### Expected behavior

env var set is readed correctly

### Actual behavior

error parsing the command line created

### CRC Logs

```shell
Step starting CRC with default bundle succeeds: command '$env:CRC_DISABLE_UPDATE_CHECK=true; crc start -p 'C:\Users\rhqp\crc-e2e\pull-secret' ', expected to succeed, exited with exit code: 1
Command stdout: 
Command stderr: true : The term 'true' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:31
+ $env:CRC_DISABLE_UPDATE_CHECK=true; crc start -p 'C:\Users\rhqp\crc-e ...
+                               ~~~~
    + CategoryInfo          : ObjectNotFound: (true:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
level=debug msg="CRC version: 2.47.0+457b65\n"
level=debug msg="OpenShift version: 4.17.14\n"
```

### Additional context

From a quick test:

```
PS C:\Users\crcqe> $env:CRC_DISABLE_UPDATE_CHECK="true"
PS C:\Users\crcqe> echo $env:CRC_DISABLE_UPDATE_CHECK  
true
PS C:\Users\crcqe> $env:CRC_DISABLE_UPDATE_CHECK='true'
PS C:\Users\crcqe> echo $env:CRC_DISABLE_UPDATE_CHECK  
true
PS C:\Users\crcqe> $env:CRC_DISABLE_UPDATE_CHECK=$true 
PS C:\Users\crcqe> echo $env:CRC_DISABLE_UPDATE_CHECK 
True
PS C:\Users\crcqe> $env:CRC_DISABLE_UPDATE_CHECK=true 
true: The term 'true' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### PR DESCRIPTION
**Pull request by albfan**
## Description

CI sets some configurations using env var, `FOO=bar`, but windows do not support that format, it should be `$env:FOO=bar;`

Fixes: #4618

### CODE REVIEW

File: test/extended/crc/cmd/cmd.go [hunk 1]
```diff
@@ -97,11 +97,23 @@ func (c Command) env() []string {
...
+		suffix = ";"
+		switch value {
+		case "true":
+			value = "$true"
+			break
+		case "false":
+			value = "$false"
+			break
+		default:
+		}
```
Comment (rohanKanojia) [inline test/extended/crc/cmd/cmd.go]: Do you think we can replace this switch statement like this?
```suggestion
                value = fmt.Sprintf("$%s", value)
```

Comment (anjannath) [reply test/extended/crc/cmd/cmd.go]: maybe the function should be called `SetBoolEnvVariable` then, because we want to append the `$` only in case of bool values

File: test/extended/crc/cmd/cmd_test.go [hunk 2]
```diff
@@ -8,15 +8,17 @@ import (
...
 		command:     "start -b bundle",
 		disableNTP:  true,
 		updateCheck: true,
 	}.ToString())
 	assert.Equal(t, "CRC_DISABLE_UPDATE_CHECK=true CRC_DEBUG_ENABLE_STOP_NTP=true crc start -b bundle", Command{
-		command:    "start -b bundle",
-		disableNTP: true,
+		command:     "start -b bundle",
+		disableNTP:  true,
+		updateCheck: false,
```
Comment (anjannath) [inline test/extended/crc/cmd/cmd_test.go:22]: could you please add some details to the commit log why this is needed now or what this fixes

Comment (adrianriobo) [reply test/extended/crc/cmd/cmd_test.go:22]: @albfan check previous comment :pray:

**Comment by albfan** [comment]
Probably fixed with a machine restart, as it is not reproducible anymore. closing by now

**Comment by cfergeau** [comment]
Some of the test failures look related to these changes:
```
 cd tools && GOBIN="/go/src/github.com/crc-org/crc/tools/bin" go install github.com/golangci/golangci-lint/cmd/golangci-lint
"/go/src/github.com/crc-org/crc/tools/bin"/golangci-lint run
test/extended/util/util.go:34:4: S1023: redundant break statement (gosimple)
			break
			^
test/extended/util/util.go:37:4: S1023: redundant break statement (gosimple)
			break
			^ 
```

File: test/extended/crc/cmd/cmd.go (hunk 1 above)
Comment (albfan) [reply test/extended/crc/cmd/cmd.go]: This cannot be applied as this deals too with the case of env var not being a bool, in which case, value is keep unmodified:

```
FOO=bar
$env:FOO=bar
```

```
BAR=true
$env:BAR=$true
```

this is problematic if we pretend to set an env var with text "true" or "false", but probably that will be never the case. If there's a need for that, then we need a way to specify that we want a $true or $false in windows

Comment (rohanKanojia) [reply test/extended/crc/cmd/cmd.go]: okay, I'm sorry I didn't know about this use case. 

marking this comment as resolved.

File: test/extended/crc/cmd/cmd_test.go (hunk 2 above)
Comment (albfan) [reply test/extended/crc/cmd/cmd_test.go:22]: I tried to be explicit about expected result from test, but updateCheck by default is false. @anjannath Should I remove this part of the change?

Comment (anjannath) [reply test/extended/crc/cmd/cmd_test.go:22]: ahh thanks, i understand now, so you wanted to make `Command.updateCheck = false` explicit, we can keep this change

File: test/extended/util/util.go [hunk 3]
```diff
@@ -22,6 +22,25 @@ var (
...
+	if runtime.GOOS == "windows" {
+		prefix = "$env:"
+		suffix = ";"
+		switch value {
+		case "true":
+			value = "$true"
+			break
+		case "false":
+			value = "$false"
+			break
```
Comment (praveenkumar) [inline test/extended/util/util.go]: why you need the break?

**Comment by praveenkumar** [comment]
```
/go/src/github.com/crc-org/crc/tools/bin"/golangci-lint run
test/extended/util/util.go:34:4: S1023: redundant break statement (gosimple)
			break
			^
test/extended/util/util.go:37:4: S1023: redundant break statement (gosimple)
			break 
```
linter is failing, make sure run `make cross-lint` after your changes to make sure it doesn't fail linting side.
